/**
 * Auto-generated barrel for the names tag.
 * Regenerated by scripts/organize-models-by-tag.mjs after each orval run.
 *
 * Local files are exported directly. Types that belong to OTHER tags
 * but are used here are re-exported as named types for convenience.
 */
export * from './addNamePageBodyDto'
export * from './chapterNameControllerAddPagePathParameters'
export * from './chapterNameControllerApprovePathParameters'
export * from './chapterNameControllerCreatePathParameters'
export * from './chapterNameControllerGetOnePathParameters'
export * from './chapterNameControllerListPathParameters'
export * from './chapterNameControllerRemovePathParameters'
export * from './chapterNameControllerRequestRevisionPathParameters'
export * from './chapterNameControllerResubmitPathParameters'
export * from './chapterNameControllerSubmitPathParameters'
export * from './chapterNameControllerUpdatePagesPathParameters'
export * from './createChapterNameBodyDto'
export * from './createChapterNameBodyDtoNamePagesItem'
export * from './nameControllerAddPagePathParameters'
export * from './nameControllerApprovePathParameters'
export * from './nameControllerGetOnePathParameters'
export * from './nameControllerListParams'
export * from './nameControllerListPathParameters'
export * from './nameControllerRequestRevisionPathParameters'
export * from './nameControllerResubmitPathParameters'
export * from './nameControllerUpdatePagesPathParameters'
export * from './nameListResDtoOutput'
export * from './nameListResDtoOutputItemsItem'
export * from './nameListResDtoOutputItemsItemKind'
export * from './nameListResDtoOutputItemsItemPagesItem'
export * from './nameListResDtoOutputItemsItemStatus'
export * from './nameResDtoOutput'
export * from './nameResDtoOutputKind'
export * from './nameResDtoOutputPagesItem'
export * from './nameResDtoOutputStatus'
export * from './updateNamePagesBodyDto'
export * from './updateNamePagesBodyDtoPagesItem'
export type { MessageResDtoOutput } from '../auth/messageResDtoOutput';
export type { ReasonBodyDto } from '../chapters/reasonBodyDto';

