/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { NameResDtoOutputKind } from './nameResDtoOutputKind';
import type { NameResDtoOutputStatus } from './nameResDtoOutputStatus';
import type { NameResDtoOutputPagesItem } from './nameResDtoOutputPagesItem';

export interface NameResDtoOutput {
  id: string;
  seriesId: string;
  /**
   * null = proposal-Name; có giá trị = Name của chapter đó
   * @nullable
   */
  chapterId: string | null;
  /**
   * null cho Name chương mẫu của proposal; N = Name của chương N (kind=CHAPTER)
   * @nullable
   */
  chapterNumber: number | null;
  /** Name storyboard kind: PROPOSAL (proposal chapter-sample) or CHAPTER (per-chapter storyboard). Values: PROPOSAL, CHAPTER */
  kind: NameResDtoOutputKind;
  /** Name/chapter-name review status. Values: DRAFT, SUBMITTED, IN_REVIEW, REVISION, APPROVED */
  status: NameResDtoOutputStatus;
  /** Tăng mỗi lần resubmit */
  version: number;
  /** Các trang vẽ thô; fileUrl là object key (R2) */
  pages: NameResDtoOutputPagesItem[];
  /**
   * ISO 8601; null khi chưa submit
   * @nullable
   */
  submittedAt: string | null;
}
