/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { AiJobResDtoOutputType } from './aiJobResDtoOutputType';
import type { AiJobResDtoOutputMode } from './aiJobResDtoOutputMode';
import type { AiJobResDtoOutputSourceType } from './aiJobResDtoOutputSourceType';
import type { AiJobResDtoOutputStatus } from './aiJobResDtoOutputStatus';
import type { AiJobResDtoOutputProposedRegionsItem } from './aiJobResDtoOutputProposedRegionsItem';

export interface AiJobResDtoOutput {
  id: string;
  /** AI job type: SEGMENT; COLOR/NUMBER are reserved for Spec 3. Values: SEGMENT, COLOR, NUMBER */
  type: AiJobResDtoOutputType;
  /**
   * Segmentation mode: MODEL (YOLO deep learning) or HEURISTIC (OpenCV baseline). Values: MODEL, HEURISTIC
   * @nullable
   */
  mode: AiJobResDtoOutputMode;
  pageId: string;
  /** Immutable stage input/output source: ORIGINAL or COMPOSITE. Values: ORIGINAL, COMPOSITE */
  sourceType: AiJobResDtoOutputSourceType;
  /** @nullable */
  sourceFileKey: string | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  sourceRevision: number | null;
  /** @nullable */
  sourceStageId: string | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   * @exclusiveMinimum
   * @nullable
   */
  sourceWidth: number | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   * @exclusiveMinimum
   * @nullable
   */
  sourceHeight: number | null;
  /** AI job lifecycle: QUEUED -> RUNNING -> SUCCEEDED | FAILED. Values: QUEUED, RUNNING, SUCCEEDED, FAILED */
  status: AiJobResDtoOutputStatus;
  /**
   * Error message when FAILED
   * @nullable
   */
  error: string | null;
  /** @nullable */
  modelVersion: string | null;
  /**
   * Returned only on job detail route
   * @nullable
   */
  proposedRegions: AiJobResDtoOutputProposedRegionsItem[] | null;
  /** @nullable */
  regionCount: number | null;
  /**
   * ISO timestamp; latest applied job is the active proposal
   * @nullable
   */
  appliedAt: string | null;
  /** @nullable */
  startedAt: string | null;
  /** @nullable */
  finishedAt: string | null;
  /**
   * Inference duration in milliseconds
   * @nullable
   */
  durationMs: number | null;
  createdAt: string;
}
