/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { AiJobResDtoOutputType } from './aiJobResDtoOutputType';
import type { AiJobResDtoOutputMode } from './aiJobResDtoOutputMode';
import type { AiJobResDtoOutputStatus } from './aiJobResDtoOutputStatus';
import type { AiJobResDtoOutputProposedRegionsItem } from './aiJobResDtoOutputProposedRegionsItem';

export interface AiJobResDtoOutput {
  id: string;
  /** AI job type: SEGMENT; COLOR/NUMBER are reserved for Spec 3. Values: SEGMENT, COLOR, NUMBER */
  type: AiJobResDtoOutputType;
  /**
   * Segmentation mode: MODEL (YOLO deep learning) or HEURISTIC (OpenCV baseline). Values: MODEL, HEURISTIC
   * @nullable
   */
  mode: AiJobResDtoOutputMode;
  pageId: string;
  /** AI job lifecycle: QUEUED -> RUNNING -> SUCCEEDED | FAILED. Values: QUEUED, RUNNING, SUCCEEDED, FAILED */
  status: AiJobResDtoOutputStatus;
  /**
   * Error message when FAILED
   * @nullable
   */
  error: string | null;
  /** @nullable */
  modelVersion: string | null;
  /**
   * Returned only on job detail route
   * @nullable
   */
  proposedRegions: AiJobResDtoOutputProposedRegionsItem[] | null;
  /** @nullable */
  regionCount: number | null;
  /**
   * ISO timestamp; latest applied job is the active proposal
   * @nullable
   */
  appliedAt: string | null;
  /** @nullable */
  startedAt: string | null;
  /** @nullable */
  finishedAt: string | null;
  /**
   * Inference duration in milliseconds
   * @nullable
   */
  durationMs: number | null;
  createdAt: string;
}
