/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { NotificationResDtoOutputType } from './notificationResDtoOutputType';

export interface NotificationResDtoOutput {
  id: string;
  /**
   * Notification type: SYSTEM, CONTRACT, TASK, DEADLINE, SURVEY, BOARD, REVIEW. Values: SYSTEM, CONTRACT, TASK, DEADLINE, SURVEY, BOARD, REVIEW
   * @nullable
   */
  type: NotificationResDtoOutputType;
  /**
   * ID thực thể liên quan (chapter/task/...)
   * @nullable
   */
  referenceId: string | null;
  /**
   * Mã action liên quan đến referenceId, ví dụ TASK_APPROVED hoặc CHAPTER_PUBLISHED
   * @nullable
   */
  referenceType: string | null;
  /**
   * Nội dung hiển thị; notification mới luôn có content
   * @nullable
   */
  content: string | null;
  isRead: boolean;
  /** ISO 8601 */
  createdAt: string;
}
