/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type {
  AddNamePageBodyDto,
  NameControllerAddPagePathParameters,
  NameControllerApprovePathParameters,
  NameControllerRequestRevisionPathParameters,
  NameControllerResubmitPathParameters,
  NameControllerUpdatePagesPathParameters,
  NameResDtoOutput,
  ReasonBodyDto,
  UpdateNamePagesBodyDto
} from '../../model/series-names';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Editor phụ trách yêu cầu sửa Name (→ REVISION)
 */
export type nameControllerRequestRevisionResponse201 = {
  data: NameResDtoOutput
  status: 201
}

export type nameControllerRequestRevisionResponse403 = {
  data: void
  status: 403
}

export type nameControllerRequestRevisionResponse404 = {
  data: void
  status: 404
}

export type nameControllerRequestRevisionResponse409 = {
  data: void
  status: 409
}
    
export type nameControllerRequestRevisionResponseSuccess = (nameControllerRequestRevisionResponse201) & {
  headers: Headers;
};
export type nameControllerRequestRevisionResponseError = (nameControllerRequestRevisionResponse403 | nameControllerRequestRevisionResponse404 | nameControllerRequestRevisionResponse409) & {
  headers: Headers;
};

export type nameControllerRequestRevisionResponse = (nameControllerRequestRevisionResponseSuccess | nameControllerRequestRevisionResponseError)

export const getNameControllerRequestRevisionUrl = ({ id, nameId }: NameControllerRequestRevisionPathParameters,) => {


  

  return `/series/${id}/names/${nameId}/request-revision`
}

export const nameControllerRequestRevision = async ({ id, nameId }: NameControllerRequestRevisionPathParameters,
    reasonBodyDto: ReasonBodyDto, options?: RequestInit): Promise<nameControllerRequestRevisionResponse> => {
  
  return customFetch<nameControllerRequestRevisionResponse>(getNameControllerRequestRevisionUrl({ id, nameId }),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reasonBodyDto,)
  }
);}


/**
 * @summary Mangaka nộp lại Name sau revision (→ IN_REVIEW, version++)
 */
export type nameControllerResubmitResponse201 = {
  data: NameResDtoOutput
  status: 201
}

export type nameControllerResubmitResponse403 = {
  data: void
  status: 403
}

export type nameControllerResubmitResponse409 = {
  data: void
  status: 409
}
    
export type nameControllerResubmitResponseSuccess = (nameControllerResubmitResponse201) & {
  headers: Headers;
};
export type nameControllerResubmitResponseError = (nameControllerResubmitResponse403 | nameControllerResubmitResponse409) & {
  headers: Headers;
};

export type nameControllerResubmitResponse = (nameControllerResubmitResponseSuccess | nameControllerResubmitResponseError)

export const getNameControllerResubmitUrl = ({ id, nameId }: NameControllerResubmitPathParameters,) => {


  

  return `/series/${id}/names/${nameId}/resubmit`
}

export const nameControllerResubmit = async ({ id, nameId }: NameControllerResubmitPathParameters, options?: RequestInit): Promise<nameControllerResubmitResponse> => {
  
  return customFetch<nameControllerResubmitResponse>(getNameControllerResubmitUrl({ id, nameId }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Editor duyệt Name (→ APPROVED; nếu proposal cũng APPROVED → READY_TO_PITCH)
 */
export type nameControllerApproveResponse201 = {
  data: NameResDtoOutput
  status: 201
}

export type nameControllerApproveResponse403 = {
  data: void
  status: 403
}

export type nameControllerApproveResponse404 = {
  data: void
  status: 404
}

export type nameControllerApproveResponse409 = {
  data: void
  status: 409
}
    
export type nameControllerApproveResponseSuccess = (nameControllerApproveResponse201) & {
  headers: Headers;
};
export type nameControllerApproveResponseError = (nameControllerApproveResponse403 | nameControllerApproveResponse404 | nameControllerApproveResponse409) & {
  headers: Headers;
};

export type nameControllerApproveResponse = (nameControllerApproveResponseSuccess | nameControllerApproveResponseError)

export const getNameControllerApproveUrl = ({ id, nameId }: NameControllerApprovePathParameters,) => {


  

  return `/series/${id}/names/${nameId}/approve`
}

export const nameControllerApprove = async ({ id, nameId }: NameControllerApprovePathParameters, options?: RequestInit): Promise<nameControllerApproveResponse> => {
  
  return customFetch<nameControllerApproveResponse>(getNameControllerApproveUrl({ id, nameId }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Mangaka thay TOÀN BỘ mảng trang Name (chỉ khi DRAFT/REVISION)
 */
export type nameControllerUpdatePagesResponse200 = {
  data: NameResDtoOutput
  status: 200
}

export type nameControllerUpdatePagesResponse403 = {
  data: void
  status: 403
}

export type nameControllerUpdatePagesResponse404 = {
  data: void
  status: 404
}

export type nameControllerUpdatePagesResponse409 = {
  data: void
  status: 409
}
    
export type nameControllerUpdatePagesResponseSuccess = (nameControllerUpdatePagesResponse200) & {
  headers: Headers;
};
export type nameControllerUpdatePagesResponseError = (nameControllerUpdatePagesResponse403 | nameControllerUpdatePagesResponse404 | nameControllerUpdatePagesResponse409) & {
  headers: Headers;
};

export type nameControllerUpdatePagesResponse = (nameControllerUpdatePagesResponseSuccess | nameControllerUpdatePagesResponseError)

export const getNameControllerUpdatePagesUrl = ({ id, nameId }: NameControllerUpdatePagesPathParameters,) => {


  

  return `/series/${id}/names/${nameId}/pages`
}

export const nameControllerUpdatePages = async ({ id, nameId }: NameControllerUpdatePagesPathParameters,
    updateNamePagesBodyDto: UpdateNamePagesBodyDto, options?: RequestInit): Promise<nameControllerUpdatePagesResponse> => {
  
  return customFetch<nameControllerUpdatePagesResponse>(getNameControllerUpdatePagesUrl({ id, nameId }),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateNamePagesBodyDto,)
  }
);}


/**
 * @summary Mangaka thêm 1 trang vào Name (append; chỉ khi DRAFT/REVISION)
 */
export type nameControllerAddPageResponse201 = {
  data: NameResDtoOutput
  status: 201
}

export type nameControllerAddPageResponse403 = {
  data: void
  status: 403
}

export type nameControllerAddPageResponse404 = {
  data: void
  status: 404
}

export type nameControllerAddPageResponse409 = {
  data: void
  status: 409
}
    
export type nameControllerAddPageResponseSuccess = (nameControllerAddPageResponse201) & {
  headers: Headers;
};
export type nameControllerAddPageResponseError = (nameControllerAddPageResponse403 | nameControllerAddPageResponse404 | nameControllerAddPageResponse409) & {
  headers: Headers;
};

export type nameControllerAddPageResponse = (nameControllerAddPageResponseSuccess | nameControllerAddPageResponseError)

export const getNameControllerAddPageUrl = ({ id, nameId }: NameControllerAddPagePathParameters,) => {


  

  return `/series/${id}/names/${nameId}/pages`
}

export const nameControllerAddPage = async ({ id, nameId }: NameControllerAddPagePathParameters,
    addNamePageBodyDto: AddNamePageBodyDto, options?: RequestInit): Promise<nameControllerAddPageResponse> => {
  
  return customFetch<nameControllerAddPageResponse>(getNameControllerAddPageUrl({ id, nameId }),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addNamePageBodyDto,)
  }
);}


