/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { ContractResDtoOutputContractType } from './contractResDtoOutputContractType';
import type { ContractResDtoOutputContractStart } from './contractResDtoOutputContractStart';
import type { ContractResDtoOutputContractEnd } from './contractResDtoOutputContractEnd';
import type { ContractResDtoOutputStatus } from './contractResDtoOutputStatus';
import type { ContractResDtoOutputMangakaSignedAt } from './contractResDtoOutputMangakaSignedAt';
import type { ContractResDtoOutputBoardSignedAt } from './contractResDtoOutputBoardSignedAt';

export interface ContractResDtoOutput {
  id: string;
  seriesId: string;
  mangakaId: string;
  /** @nullable */
  editorId: string | null;
  /** @nullable */
  boardDecisionId: string | null;
  /** @nullable */
  sourceTransferRequestId?: string | null;
  contractType: ContractResDtoOutputContractType;
  /** @nullable */
  valuationAmount: number | null;
  /** @nullable */
  publisherOwnershipPct: number | null;
  /** @nullable */
  mangakaOwnershipPct: number | null;
  /** @nullable */
  terminationClause: string | null;
  /** @nullable */
  contractStart: ContractResDtoOutputContractStart;
  /** @nullable */
  contractEnd: ContractResDtoOutputContractEnd;
  status: ContractResDtoOutputStatus;
  /** @nullable */
  mangakaSignedAt: ContractResDtoOutputMangakaSignedAt;
  /** @nullable */
  boardSignedAt: ContractResDtoOutputBoardSignedAt;
  createdAt: unknown;
}
