/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */

/**
 * Trạng thái điều kiện giải ngân: PENDING (chờ đạt) | ACHIEVED (đã đạt) | PAID (đã chi) | CANCELLED (đã huỷ) | MISSED (hết hạn không đạt) | DISABLED (tạm dừng khi series HIATUS — BR-CONTRACT-07). Values: PENDING, ACHIEVED, PAID, CANCELLED, MISSED, DISABLED
 */
export type PaymentConditionListResDtoOutputDataItemStatus = typeof PaymentConditionListResDtoOutputDataItemStatus[keyof typeof PaymentConditionListResDtoOutputDataItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentConditionListResDtoOutputDataItemStatus = {
  PENDING: 'PENDING',
  ACHIEVED: 'ACHIEVED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
  MISSED: 'MISSED',
  DISABLED: 'DISABLED',
} as const;
