/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type {
  CounterDeadlineBodyDto,
  CreateDeadlineRequestBodyDto,
  DeadlineControllerAgreePathParameters,
  DeadlineControllerCounterPathParameters,
  DeadlineControllerFinalizePathParameters,
  DeadlineControllerGetOnePathParameters,
  DeadlineControllerListParams,
  DeadlineControllerRejectPathParameters,
  DeadlineControllerWithdrawPathParameters,
  DeadlineReasonBodyDto,
  DeadlineRequestListResDtoOutput,
  DeadlineRequestResDtoOutput
} from '../../model/deadline-requests';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Mangaka/Editor tạo yêu cầu đổi deadline → PROPOSED
 */
export type deadlineControllerCreateResponse201 = {
  data: DeadlineRequestResDtoOutput
  status: 201
}

export type deadlineControllerCreateResponse403 = {
  data: void
  status: 403
}

export type deadlineControllerCreateResponse404 = {
  data: void
  status: 404
}

export type deadlineControllerCreateResponse409 = {
  data: void
  status: 409
}
    
export type deadlineControllerCreateResponseSuccess = (deadlineControllerCreateResponse201) & {
  headers: Headers;
};
export type deadlineControllerCreateResponseError = (deadlineControllerCreateResponse403 | deadlineControllerCreateResponse404 | deadlineControllerCreateResponse409) & {
  headers: Headers;
};

export type deadlineControllerCreateResponse = (deadlineControllerCreateResponseSuccess | deadlineControllerCreateResponseError)

export const getDeadlineControllerCreateUrl = () => {


  

  return `/deadline-requests`
}

export const deadlineControllerCreate = async (createDeadlineRequestBodyDto: CreateDeadlineRequestBodyDto, options?: RequestInit): Promise<deadlineControllerCreateResponse> => {
  
  return customFetch<deadlineControllerCreateResponse>(getDeadlineControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createDeadlineRequestBodyDto,)
  }
);}


/**
 * @summary List deadline-request theo chapter (scope theo role)
 */
export type deadlineControllerListResponse200 = {
  data: DeadlineRequestListResDtoOutput
  status: 200
}

export type deadlineControllerListResponse403 = {
  data: void
  status: 403
}

export type deadlineControllerListResponse404 = {
  data: void
  status: 404
}
    
export type deadlineControllerListResponseSuccess = (deadlineControllerListResponse200) & {
  headers: Headers;
};
export type deadlineControllerListResponseError = (deadlineControllerListResponse403 | deadlineControllerListResponse404) & {
  headers: Headers;
};

export type deadlineControllerListResponse = (deadlineControllerListResponseSuccess | deadlineControllerListResponseError)

export const getDeadlineControllerListUrl = (params: DeadlineControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/deadline-requests?${stringifiedParams}` : `/deadline-requests`
}

export const deadlineControllerList = async (params: DeadlineControllerListParams, options?: RequestInit): Promise<deadlineControllerListResponse> => {
  
  return customFetch<deadlineControllerListResponse>(getDeadlineControllerListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Bên kia đề xuất deadline khác → COUNTER_PROPOSED
 */
export type deadlineControllerCounterResponse201 = {
  data: DeadlineRequestResDtoOutput
  status: 201
}

export type deadlineControllerCounterResponse403 = {
  data: void
  status: 403
}

export type deadlineControllerCounterResponse404 = {
  data: void
  status: 404
}

export type deadlineControllerCounterResponse409 = {
  data: void
  status: 409
}
    
export type deadlineControllerCounterResponseSuccess = (deadlineControllerCounterResponse201) & {
  headers: Headers;
};
export type deadlineControllerCounterResponseError = (deadlineControllerCounterResponse403 | deadlineControllerCounterResponse404 | deadlineControllerCounterResponse409) & {
  headers: Headers;
};

export type deadlineControllerCounterResponse = (deadlineControllerCounterResponseSuccess | deadlineControllerCounterResponseError)

export const getDeadlineControllerCounterUrl = ({ id }: DeadlineControllerCounterPathParameters,) => {


  

  return `/deadline-requests/${id}/counter`
}

export const deadlineControllerCounter = async ({ id }: DeadlineControllerCounterPathParameters,
    counterDeadlineBodyDto: CounterDeadlineBodyDto, options?: RequestInit): Promise<deadlineControllerCounterResponse> => {
  
  return customFetch<deadlineControllerCounterResponse>(getDeadlineControllerCounterUrl({ id }),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      counterDeadlineBodyDto,)
  }
);}


/**
 * @summary Bên kia đồng ý → AGREED_BY_PARTIES
 */
export type deadlineControllerAgreeResponse201 = {
  data: DeadlineRequestResDtoOutput
  status: 201
}

export type deadlineControllerAgreeResponse403 = {
  data: void
  status: 403
}

export type deadlineControllerAgreeResponse404 = {
  data: void
  status: 404
}

export type deadlineControllerAgreeResponse409 = {
  data: void
  status: 409
}
    
export type deadlineControllerAgreeResponseSuccess = (deadlineControllerAgreeResponse201) & {
  headers: Headers;
};
export type deadlineControllerAgreeResponseError = (deadlineControllerAgreeResponse403 | deadlineControllerAgreeResponse404 | deadlineControllerAgreeResponse409) & {
  headers: Headers;
};

export type deadlineControllerAgreeResponse = (deadlineControllerAgreeResponseSuccess | deadlineControllerAgreeResponseError)

export const getDeadlineControllerAgreeUrl = ({ id }: DeadlineControllerAgreePathParameters,) => {


  

  return `/deadline-requests/${id}/agree`
}

export const deadlineControllerAgree = async ({ id }: DeadlineControllerAgreePathParameters, options?: RequestInit): Promise<deadlineControllerAgreeResponse> => {
  
  return customFetch<deadlineControllerAgreeResponse>(getDeadlineControllerAgreeUrl({ id }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Bên kia từ chối → ESCALATED (leo Board, defer B5)
 */
export type deadlineControllerRejectResponse201 = {
  data: DeadlineRequestResDtoOutput
  status: 201
}

export type deadlineControllerRejectResponse403 = {
  data: void
  status: 403
}

export type deadlineControllerRejectResponse404 = {
  data: void
  status: 404
}

export type deadlineControllerRejectResponse409 = {
  data: void
  status: 409
}
    
export type deadlineControllerRejectResponseSuccess = (deadlineControllerRejectResponse201) & {
  headers: Headers;
};
export type deadlineControllerRejectResponseError = (deadlineControllerRejectResponse403 | deadlineControllerRejectResponse404 | deadlineControllerRejectResponse409) & {
  headers: Headers;
};

export type deadlineControllerRejectResponse = (deadlineControllerRejectResponseSuccess | deadlineControllerRejectResponseError)

export const getDeadlineControllerRejectUrl = ({ id }: DeadlineControllerRejectPathParameters,) => {


  

  return `/deadline-requests/${id}/reject`
}

export const deadlineControllerReject = async ({ id }: DeadlineControllerRejectPathParameters,
    deadlineReasonBodyDto: DeadlineReasonBodyDto, options?: RequestInit): Promise<deadlineControllerRejectResponse> => {
  
  return customFetch<deadlineControllerRejectResponse>(getDeadlineControllerRejectUrl({ id }),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deadlineReasonBodyDto,)
  }
);}


/**
 * @summary Người khởi tạo rút yêu cầu → REJECTED (terminal)
 */
export type deadlineControllerWithdrawResponse201 = {
  data: DeadlineRequestResDtoOutput
  status: 201
}

export type deadlineControllerWithdrawResponse403 = {
  data: void
  status: 403
}

export type deadlineControllerWithdrawResponse404 = {
  data: void
  status: 404
}

export type deadlineControllerWithdrawResponse409 = {
  data: void
  status: 409
}
    
export type deadlineControllerWithdrawResponseSuccess = (deadlineControllerWithdrawResponse201) & {
  headers: Headers;
};
export type deadlineControllerWithdrawResponseError = (deadlineControllerWithdrawResponse403 | deadlineControllerWithdrawResponse404 | deadlineControllerWithdrawResponse409) & {
  headers: Headers;
};

export type deadlineControllerWithdrawResponse = (deadlineControllerWithdrawResponseSuccess | deadlineControllerWithdrawResponseError)

export const getDeadlineControllerWithdrawUrl = ({ id }: DeadlineControllerWithdrawPathParameters,) => {


  

  return `/deadline-requests/${id}/withdraw`
}

export const deadlineControllerWithdraw = async ({ id }: DeadlineControllerWithdrawPathParameters, options?: RequestInit): Promise<deadlineControllerWithdrawResponse> => {
  
  return customFetch<deadlineControllerWithdrawResponse>(getDeadlineControllerWithdrawUrl({ id }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Editor chốt: !affectsSlot → APPROVED (cập nhật Schedule) | affectsSlot → BOARD_REVIEW (defer B5)
 */
export type deadlineControllerFinalizeResponse201 = {
  data: DeadlineRequestResDtoOutput
  status: 201
}

export type deadlineControllerFinalizeResponse403 = {
  data: void
  status: 403
}

export type deadlineControllerFinalizeResponse404 = {
  data: void
  status: 404
}

export type deadlineControllerFinalizeResponse409 = {
  data: void
  status: 409
}
    
export type deadlineControllerFinalizeResponseSuccess = (deadlineControllerFinalizeResponse201) & {
  headers: Headers;
};
export type deadlineControllerFinalizeResponseError = (deadlineControllerFinalizeResponse403 | deadlineControllerFinalizeResponse404 | deadlineControllerFinalizeResponse409) & {
  headers: Headers;
};

export type deadlineControllerFinalizeResponse = (deadlineControllerFinalizeResponseSuccess | deadlineControllerFinalizeResponseError)

export const getDeadlineControllerFinalizeUrl = ({ id }: DeadlineControllerFinalizePathParameters,) => {


  

  return `/deadline-requests/${id}/finalize`
}

export const deadlineControllerFinalize = async ({ id }: DeadlineControllerFinalizePathParameters, options?: RequestInit): Promise<deadlineControllerFinalizeResponse> => {
  
  return customFetch<deadlineControllerFinalizeResponse>(getDeadlineControllerFinalizeUrl({ id }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Chi tiết 1 deadline-request (scope theo role)
 */
export type deadlineControllerGetOneResponse200 = {
  data: DeadlineRequestResDtoOutput
  status: 200
}

export type deadlineControllerGetOneResponse403 = {
  data: void
  status: 403
}

export type deadlineControllerGetOneResponse404 = {
  data: void
  status: 404
}
    
export type deadlineControllerGetOneResponseSuccess = (deadlineControllerGetOneResponse200) & {
  headers: Headers;
};
export type deadlineControllerGetOneResponseError = (deadlineControllerGetOneResponse403 | deadlineControllerGetOneResponse404) & {
  headers: Headers;
};

export type deadlineControllerGetOneResponse = (deadlineControllerGetOneResponseSuccess | deadlineControllerGetOneResponseError)

export const getDeadlineControllerGetOneUrl = ({ id }: DeadlineControllerGetOnePathParameters,) => {


  

  return `/deadline-requests/${id}`
}

export const deadlineControllerGetOne = async ({ id }: DeadlineControllerGetOnePathParameters, options?: RequestInit): Promise<deadlineControllerGetOneResponse> => {
  
  return customFetch<deadlineControllerGetOneResponse>(getDeadlineControllerGetOneUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


