/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  DeadlineRequestListResDtoOutput,
  DeadlineRequestResDtoOutput
} from '../../model/deadline-requests';


export const getDeadlineControllerCreateResponseMock = (overrideResponse: Partial< DeadlineRequestResDtoOutput > = {}): DeadlineRequestResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), scheduleId: faker.string.alpha({length: {min: 10, max: 20}}), chapterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), seriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), lastProposedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), currentDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reason: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), affectsSlot: faker.datatype.boolean(), status: faker.helpers.arrayElement(['PROPOSED','COUNTER_PROPOSED','AGREED_BY_PARTIES','BOARD_REVIEW','ESCALATED','APPROVED','REJECTED'] as const), boardReviewedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), resolvedAt: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), series: {id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}})}, chapter: {id: faker.string.alpha({length: {min: 10, max: 20}}), chapterNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null])}, ...overrideResponse})

export const getDeadlineControllerListResponseMock = (overrideResponse: Partial< DeadlineRequestListResDtoOutput > = {}): DeadlineRequestListResDtoOutput => ({items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), scheduleId: faker.string.alpha({length: {min: 10, max: 20}}), chapterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), seriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), lastProposedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), currentDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reason: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), affectsSlot: faker.datatype.boolean(), status: faker.helpers.arrayElement(['PROPOSED','COUNTER_PROPOSED','AGREED_BY_PARTIES','BOARD_REVIEW','ESCALATED','APPROVED','REJECTED'] as const), boardReviewedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), resolvedAt: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), series: {id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}})}, chapter: {id: faker.string.alpha({length: {min: 10, max: 20}}), chapterNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null])}})), ...overrideResponse})

export const getDeadlineControllerCounterResponseMock = (overrideResponse: Partial< DeadlineRequestResDtoOutput > = {}): DeadlineRequestResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), scheduleId: faker.string.alpha({length: {min: 10, max: 20}}), chapterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), seriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), lastProposedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), currentDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reason: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), affectsSlot: faker.datatype.boolean(), status: faker.helpers.arrayElement(['PROPOSED','COUNTER_PROPOSED','AGREED_BY_PARTIES','BOARD_REVIEW','ESCALATED','APPROVED','REJECTED'] as const), boardReviewedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), resolvedAt: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), series: {id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}})}, chapter: {id: faker.string.alpha({length: {min: 10, max: 20}}), chapterNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null])}, ...overrideResponse})

export const getDeadlineControllerAgreeResponseMock = (overrideResponse: Partial< DeadlineRequestResDtoOutput > = {}): DeadlineRequestResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), scheduleId: faker.string.alpha({length: {min: 10, max: 20}}), chapterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), seriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), lastProposedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), currentDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reason: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), affectsSlot: faker.datatype.boolean(), status: faker.helpers.arrayElement(['PROPOSED','COUNTER_PROPOSED','AGREED_BY_PARTIES','BOARD_REVIEW','ESCALATED','APPROVED','REJECTED'] as const), boardReviewedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), resolvedAt: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), series: {id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}})}, chapter: {id: faker.string.alpha({length: {min: 10, max: 20}}), chapterNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null])}, ...overrideResponse})

export const getDeadlineControllerRejectResponseMock = (overrideResponse: Partial< DeadlineRequestResDtoOutput > = {}): DeadlineRequestResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), scheduleId: faker.string.alpha({length: {min: 10, max: 20}}), chapterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), seriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), lastProposedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), currentDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reason: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), affectsSlot: faker.datatype.boolean(), status: faker.helpers.arrayElement(['PROPOSED','COUNTER_PROPOSED','AGREED_BY_PARTIES','BOARD_REVIEW','ESCALATED','APPROVED','REJECTED'] as const), boardReviewedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), resolvedAt: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), series: {id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}})}, chapter: {id: faker.string.alpha({length: {min: 10, max: 20}}), chapterNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null])}, ...overrideResponse})

export const getDeadlineControllerWithdrawResponseMock = (overrideResponse: Partial< DeadlineRequestResDtoOutput > = {}): DeadlineRequestResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), scheduleId: faker.string.alpha({length: {min: 10, max: 20}}), chapterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), seriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), lastProposedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), currentDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reason: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), affectsSlot: faker.datatype.boolean(), status: faker.helpers.arrayElement(['PROPOSED','COUNTER_PROPOSED','AGREED_BY_PARTIES','BOARD_REVIEW','ESCALATED','APPROVED','REJECTED'] as const), boardReviewedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), resolvedAt: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), series: {id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}})}, chapter: {id: faker.string.alpha({length: {min: 10, max: 20}}), chapterNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null])}, ...overrideResponse})

export const getDeadlineControllerFinalizeResponseMock = (overrideResponse: Partial< DeadlineRequestResDtoOutput > = {}): DeadlineRequestResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), scheduleId: faker.string.alpha({length: {min: 10, max: 20}}), chapterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), seriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), lastProposedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), currentDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reason: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), affectsSlot: faker.datatype.boolean(), status: faker.helpers.arrayElement(['PROPOSED','COUNTER_PROPOSED','AGREED_BY_PARTIES','BOARD_REVIEW','ESCALATED','APPROVED','REJECTED'] as const), boardReviewedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), resolvedAt: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), series: {id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}})}, chapter: {id: faker.string.alpha({length: {min: 10, max: 20}}), chapterNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null])}, ...overrideResponse})

export const getDeadlineControllerBoardResolveResponseMock = (overrideResponse: Partial< DeadlineRequestResDtoOutput > = {}): DeadlineRequestResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), scheduleId: faker.string.alpha({length: {min: 10, max: 20}}), chapterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), seriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), lastProposedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), currentDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reason: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), affectsSlot: faker.datatype.boolean(), status: faker.helpers.arrayElement(['PROPOSED','COUNTER_PROPOSED','AGREED_BY_PARTIES','BOARD_REVIEW','ESCALATED','APPROVED','REJECTED'] as const), boardReviewedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), resolvedAt: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), series: {id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}})}, chapter: {id: faker.string.alpha({length: {min: 10, max: 20}}), chapterNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null])}, ...overrideResponse})

export const getDeadlineControllerGetOneResponseMock = (overrideResponse: Partial< DeadlineRequestResDtoOutput > = {}): DeadlineRequestResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), scheduleId: faker.string.alpha({length: {min: 10, max: 20}}), chapterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), seriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), lastProposedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), currentDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), requestedDeadline: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reason: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), affectsSlot: faker.datatype.boolean(), status: faker.helpers.arrayElement(['PROPOSED','COUNTER_PROPOSED','AGREED_BY_PARTIES','BOARD_REVIEW','ESCALATED','APPROVED','REJECTED'] as const), boardReviewedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), resolvedAt: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), series: {id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}})}, chapter: {id: faker.string.alpha({length: {min: 10, max: 20}}), chapterNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null])}, ...overrideResponse})


export const getDeadlineControllerCreateMockHandler = (overrideResponse?: DeadlineRequestResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DeadlineRequestResDtoOutput> | DeadlineRequestResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/deadline-requests', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeadlineControllerCreateResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeadlineControllerListMockHandler = (overrideResponse?: DeadlineRequestListResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DeadlineRequestListResDtoOutput> | DeadlineRequestListResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/deadline-requests', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeadlineControllerListResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeadlineControllerCounterMockHandler = (overrideResponse?: DeadlineRequestResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DeadlineRequestResDtoOutput> | DeadlineRequestResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/deadline-requests/:id/counter', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeadlineControllerCounterResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeadlineControllerAgreeMockHandler = (overrideResponse?: DeadlineRequestResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DeadlineRequestResDtoOutput> | DeadlineRequestResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/deadline-requests/:id/agree', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeadlineControllerAgreeResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeadlineControllerRejectMockHandler = (overrideResponse?: DeadlineRequestResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DeadlineRequestResDtoOutput> | DeadlineRequestResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/deadline-requests/:id/reject', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeadlineControllerRejectResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeadlineControllerWithdrawMockHandler = (overrideResponse?: DeadlineRequestResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DeadlineRequestResDtoOutput> | DeadlineRequestResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/deadline-requests/:id/withdraw', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeadlineControllerWithdrawResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeadlineControllerFinalizeMockHandler = (overrideResponse?: DeadlineRequestResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DeadlineRequestResDtoOutput> | DeadlineRequestResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/deadline-requests/:id/finalize', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeadlineControllerFinalizeResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeadlineControllerBoardResolveMockHandler = (overrideResponse?: DeadlineRequestResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DeadlineRequestResDtoOutput> | DeadlineRequestResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/deadline-requests/:id/board-resolve', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeadlineControllerBoardResolveResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeadlineControllerGetOneMockHandler = (overrideResponse?: DeadlineRequestResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DeadlineRequestResDtoOutput> | DeadlineRequestResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/deadline-requests/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeadlineControllerGetOneResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getDeadlineRequestsMock = () => [
  getDeadlineControllerCreateMockHandler(),
  getDeadlineControllerListMockHandler(),
  getDeadlineControllerCounterMockHandler(),
  getDeadlineControllerAgreeMockHandler(),
  getDeadlineControllerRejectMockHandler(),
  getDeadlineControllerWithdrawMockHandler(),
  getDeadlineControllerFinalizeMockHandler(),
  getDeadlineControllerBoardResolveMockHandler(),
  getDeadlineControllerGetOneMockHandler()
]
