/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */

/**
 * Audited entity type: SERIES, MANUSCRIPT, PAGE, CHAPTER, TASK, DEADLINE_REQUEST, USER, REGION, APP_CONFIG, CONTRACT, BOARD_DECISION, REPRINT_REQUEST, TRANSFER_REQUEST. Values: SERIES, MANUSCRIPT, PAGE, CHAPTER, TASK, DEADLINE_REQUEST, USER, REGION, APP_CONFIG, CONTRACT, BOARD_DECISION, REPRINT_REQUEST, TRANSFER_REQUEST, PAYMENT_RECORD, SURVEY_PERIOD, PUBLICATION_VERSION
 */
export type AuditLogListResDtoOutputItemsItemEntityType = typeof AuditLogListResDtoOutputItemsItemEntityType[keyof typeof AuditLogListResDtoOutputItemsItemEntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditLogListResDtoOutputItemsItemEntityType = {
  SERIES: 'SERIES',
  MANUSCRIPT: 'MANUSCRIPT',
  PAGE: 'PAGE',
  CHAPTER: 'CHAPTER',
  TASK: 'TASK',
  DEADLINE_REQUEST: 'DEADLINE_REQUEST',
  USER: 'USER',
  REGION: 'REGION',
  APP_CONFIG: 'APP_CONFIG',
  CONTRACT: 'CONTRACT',
  BOARD_DECISION: 'BOARD_DECISION',
  REPRINT_REQUEST: 'REPRINT_REQUEST',
  TRANSFER_REQUEST: 'TRANSFER_REQUEST',
  PAYMENT_RECORD: 'PAYMENT_RECORD',
  SURVEY_PERIOD: 'SURVEY_PERIOD',
  PUBLICATION_VERSION: 'PUBLICATION_VERSION',
} as const;
