/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { CreateProposalBodyDtoPublicationType } from './createProposalBodyDtoPublicationType'
import type { CreateProposalBodyDtoNamePagesItem } from './createProposalBodyDtoNamePagesItem'
import type { CreateProposalBodyDtoRelationshipType } from './createProposalBodyDtoRelationshipType'

export interface CreateProposalBodyDto {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string
  /** @minLength 1 */
  coverImage?: string
  genre?: string
  demographic?: string
  /** Publication cadence: WEEKLY, MONTHLY, IRREGULAR. Values: WEEKLY, MONTHLY, IRREGULAR */
  publicationType?: CreateProposalBodyDtoPublicationType
  /** @maxLength 5000 */
  synopsis?: string
  characterDesigns?: string[]
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  estimatedLength?: number
  namePages?: CreateProposalBodyDtoNamePagesItem[]
  parentSeriesId?: string
  /** Relationship to parent series: SEQUEL, SPINOFF, SIDE_STORY, REBOOT. Values: SEQUEL, SPINOFF, SIDE_STORY, REBOOT */
  relationshipType?: CreateProposalBodyDtoRelationshipType
}
