/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { CreateProposalResDtoOutputNameKind } from './createProposalResDtoOutputNameKind';
import type { CreateProposalResDtoOutputNameStatus } from './createProposalResDtoOutputNameStatus';
import type { CreateProposalResDtoOutputNamePagesItem } from './createProposalResDtoOutputNamePagesItem';

export type CreateProposalResDtoOutputName = {
  id: string;
  seriesId: string;
  /**
   * null cho Name chương mẫu của proposal
   * @nullable
   */
  chapterNumber: number | null;
  /** Name storyboard kind: PROPOSAL (proposal chapter-sample) or CHAPTER (per-chapter storyboard). Values: PROPOSAL, CHAPTER */
  kind: CreateProposalResDtoOutputNameKind;
  /** Name/chapter-name review status. Values: DRAFT, SUBMITTED, IN_REVIEW, REVISION, APPROVED */
  status: CreateProposalResDtoOutputNameStatus;
  /** Tăng mỗi lần resubmit */
  version: number;
  /**
   * ISO 8601; null khi chưa submit
   * @nullable
   */
  submittedAt: string | null;
  /** Các trang vẽ thô; fileUrl là object key (R2) */
  pages: CreateProposalResDtoOutputNamePagesItem[];
};
