/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * The WDP API description
 * OpenAPI spec version: 1.0
 */
import type { CreateProposalResDtoOutputSeries } from './createProposalResDtoOutputSeries';
import type { CreateProposalResDtoOutputName } from './createProposalResDtoOutputName';

export interface CreateProposalResDtoOutput {
  series: CreateProposalResDtoOutputSeries;
  name: CreateProposalResDtoOutputName;
}
