/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { CreateProposalResDtoOutputSeriesGenresItem } from './createProposalResDtoOutputSeriesGenresItem';
import type { CreateProposalResDtoOutputSeriesDemographic } from './createProposalResDtoOutputSeriesDemographic';
import type { CreateProposalResDtoOutputSeriesPublicationType } from './createProposalResDtoOutputSeriesPublicationType';
import type { CreateProposalResDtoOutputSeriesStatus } from './createProposalResDtoOutputSeriesStatus';
import type { CreateProposalResDtoOutputSeriesRelationshipType } from './createProposalResDtoOutputSeriesRelationshipType';
import type { CreateProposalResDtoOutputSeriesFranchiseConsentStatus } from './createProposalResDtoOutputSeriesFranchiseConsentStatus';
import type { CreateProposalResDtoOutputSeriesCompletionProposal } from './createProposalResDtoOutputSeriesCompletionProposal';
import type { CreateProposalResDtoOutputSeriesProposal } from './createProposalResDtoOutputSeriesProposal';

export type CreateProposalResDtoOutputSeries = {
  id: string;
  /** Chủ sở hữu series (Mangaka tạo proposal) */
  mangakaId: string;
  /**
   * Editor phụ trách; null = đang ở hàng đợi review chưa ai nhận
   * @nullable
   */
  editorId: string | null;
  /**
   * Đồng sở hữu sau PARTIAL_TRANSFER (BE-B); null nếu không có
   * @nullable
   */
  coOwnerId: string | null;
  /**
   * Series gốc nếu là kế nhiệm (sequel/spinoff)
   * @nullable
   */
  parentSeriesId: string | null;
  title: string;
  /**
   * Object key ảnh bìa (R2) — đổi sang signed GET để hiển thị; KHÔNG phải URL
   * @nullable
   */
  coverImage: string | null;
  genres: CreateProposalResDtoOutputSeriesGenresItem[];
  /**
   * Phân khúc độc giả: SHONEN, SEINEN, SHOJO, JOSEI, KODOMO. Values: SHONEN, SEINEN, SHOJO, JOSEI, KODOMO
   * @nullable
   */
  demographic: CreateProposalResDtoOutputSeriesDemographic;
  /**
   * Publication cadence: WEEKLY, MONTHLY, IRREGULAR. Values: WEEKLY, MONTHLY, IRREGULAR
   * @nullable
   */
  publicationType: CreateProposalResDtoOutputSeriesPublicationType;
  /**
   * Tạp chí Board chọn khi serial hoá (Flow 1 slot); null tới khi series SERIALIZED
   * @nullable
   */
  magazine: string | null;
  /**
   * Số kỳ (issue) series bắt đầu đăng (Flow 1 slot); null tới khi series SERIALIZED
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  startIssueNumber: number | null;
  /** Series state machine status. Values: DRAFT, IN_REVIEW, READY_TO_PITCH, PITCHED, SERIALIZED, HIATUS, COMPLETING, CANCELLING, COMPLETED, CANCELLED, REJECTED, ABANDONED, WITHDRAWN */
  status: CreateProposalResDtoOutputSeriesStatus;
  /**
   * Lý do của lần đổi status gần nhất (reject/withdraw/cancel...); null nếu không có
   * @nullable
   */
  statusReason: string | null;
  /**
   * Relationship to parent series: SEQUEL, SPINOFF, SIDE_STORY, REBOOT. Values: SEQUEL, SPINOFF, SIDE_STORY, REBOOT
   * @nullable
   */
  relationshipType: CreateProposalResDtoOutputSeriesRelationshipType;
  /**
   * Gate đồng ý franchise: null=không gate; PENDING chờ Mangaka gốc; APPROVED/REJECTED đã quyết
   * @nullable
   */
  franchiseConsentStatus: CreateProposalResDtoOutputSeriesFranchiseConsentStatus;
  /** ISO 8601 */
  createdAt: string;
  /**
   * Mốc Editor bắt đầu review (set 1 lần ở action review đầu); có giá trị = khoá nhả series
   * @nullable
   */
  reviewStartedAt: string | null;
  /**
   * Đề xuất kết thúc tự nhiên (PB-06); null nếu chưa đề xuất
   * @nullable
   */
  completionProposal: CreateProposalResDtoOutputSeriesCompletionProposal;
  /**
   * Hồ sơ proposal (nhúng trong Series); null nếu chưa có
   * @nullable
   */
  proposal: CreateProposalResDtoOutputSeriesProposal;
};
