/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { SeriesListResDtoOutputItemsItemMangaka } from './seriesListResDtoOutputItemsItemMangaka';
import type { SeriesListResDtoOutputItemsItemEditor } from './seriesListResDtoOutputItemsItemEditor';
import type { SeriesListResDtoOutputItemsItemGenresItem } from './seriesListResDtoOutputItemsItemGenresItem';
import type { SeriesListResDtoOutputItemsItemDemographic } from './seriesListResDtoOutputItemsItemDemographic';
import type { SeriesListResDtoOutputItemsItemPublicationType } from './seriesListResDtoOutputItemsItemPublicationType';
import type { SeriesListResDtoOutputItemsItemStatus } from './seriesListResDtoOutputItemsItemStatus';

export type SeriesListResDtoOutputItemsItem = {
  id: string;
  /** Chủ sở hữu series (Mangaka tạo proposal) */
  mangakaId: string;
  /**
   * Editor phụ trách; null = đang ở hàng đợi review chưa ai nhận
   * @nullable
   */
  editorId: string | null;
  /** Thông tin hiển thị chủ series — CÓ ở GET /series + GET /series/:id */
  mangaka?: SeriesListResDtoOutputItemsItemMangaka;
  /**
   * Thông tin hiển thị editor; null = hàng đợi — CÓ ở GET /series + GET /series/:id
   * @nullable
   */
  editor?: SeriesListResDtoOutputItemsItemEditor;
  title: string;
  /**
   * Object key ảnh bìa (R2) — đổi sang signed GET để hiển thị; KHÔNG phải URL
   * @nullable
   */
  coverImage: string | null;
  genres: SeriesListResDtoOutputItemsItemGenresItem[];
  /**
   * Phân khúc độc giả: SHONEN, SEINEN, SHOJO, JOSEI, KODOMO. Values: SHONEN, SEINEN, SHOJO, JOSEI, KODOMO
   * @nullable
   */
  demographic: SeriesListResDtoOutputItemsItemDemographic;
  /**
   * Publication cadence: WEEKLY, MONTHLY, IRREGULAR. Values: WEEKLY, MONTHLY, IRREGULAR
   * @nullable
   */
  publicationType: SeriesListResDtoOutputItemsItemPublicationType;
  /**
   * Tạp chí Board chọn khi serial hoá (Flow 1 slot); null tới khi series SERIALIZED
   * @nullable
   */
  magazine: string | null;
  /** Series state machine status. Values: DRAFT, IN_REVIEW, READY_TO_PITCH, PITCHED, SERIALIZED, HIATUS, COMPLETING, CANCELLING, COMPLETED, CANCELLED, REJECTED, ABANDONED, WITHDRAWN */
  status: SeriesListResDtoOutputItemsItemStatus;
  /** ISO 8601 */
  createdAt: string;
};
