/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { UpdateProposalBodyDtoGenresItem } from './updateProposalBodyDtoGenresItem';
import type { UpdateProposalBodyDtoDemographic } from './updateProposalBodyDtoDemographic';
import type { UpdateProposalBodyDtoPublicationType } from './updateProposalBodyDtoPublicationType';

export interface UpdateProposalBodyDto {
  /**
   * @minLength 1
   * @maxLength 200
   * @nullable
   */
  title?: string | null;
  /**
   * @minLength 1
   * @nullable
   */
  coverImage?: string | null;
  /** @nullable */
  genres?: UpdateProposalBodyDtoGenresItem[] | null;
  /**
   * Phân khúc độc giả: SHONEN, SEINEN, SHOJO, JOSEI, KODOMO. Values: SHONEN, SEINEN, SHOJO, JOSEI, KODOMO
   * @nullable
   */
  demographic?: UpdateProposalBodyDtoDemographic;
  /**
   * Publication cadence: WEEKLY, MONTHLY, IRREGULAR. Values: WEEKLY, MONTHLY, IRREGULAR
   * @nullable
   */
  publicationType?: UpdateProposalBodyDtoPublicationType;
  /**
   * @maxLength 5000
   * @nullable
   */
  synopsis?: string | null;
  /** @nullable */
  characterDesigns?: string[] | null;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  estimatedLength?: number | null;
}
