/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type {
  SignDownloadBodyDto,
  SignDownloadResDtoOutput,
  SignUploadBodyDto,
  SignUploadResDtoOutput
} from '../../model/uploads';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Xin signed URL upload (presigned PUT) lên R2; validate type/size; tạo Asset; trả uploadUrl + key
 */
export type storageControllerSignUploadResponse201 = {
  data: SignUploadResDtoOutput
  status: 201
}
    
export type storageControllerSignUploadResponseSuccess = (storageControllerSignUploadResponse201) & {
  headers: Headers;
};
;

export type storageControllerSignUploadResponse = (storageControllerSignUploadResponseSuccess)

export const getStorageControllerSignUploadUrl = () => {


  

  return `/uploads/sign`
}

export const storageControllerSignUpload = async (signUploadBodyDto: SignUploadBodyDto, options?: RequestInit): Promise<storageControllerSignUploadResponse> => {
  
  return customFetch<storageControllerSignUploadResponse>(getStorageControllerSignUploadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signUploadBodyDto,)
  }
);}


/**
 * @summary Xin signed URL download (presigned GET) cho 1 object key (chủ sở hữu / EDITOR / BOARD)
 */
export type storageControllerSignDownloadResponse201 = {
  data: SignDownloadResDtoOutput
  status: 201
}
    
export type storageControllerSignDownloadResponseSuccess = (storageControllerSignDownloadResponse201) & {
  headers: Headers;
};
;

export type storageControllerSignDownloadResponse = (storageControllerSignDownloadResponseSuccess)

export const getStorageControllerSignDownloadUrl = () => {


  

  return `/uploads/sign-download`
}

export const storageControllerSignDownload = async (signDownloadBodyDto: SignDownloadBodyDto, options?: RequestInit): Promise<storageControllerSignDownloadResponse> => {
  
  return customFetch<storageControllerSignDownloadResponse>(getStorageControllerSignDownloadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signDownloadBodyDto,)
  }
);}


