/**
 * Auto-generated barrel for the tankobon tag.
 * Regenerated by scripts/organize-models-by-tag.mjs after each orval run.
 *
 * Local files are exported directly. Types that belong to OTHER tags
 * but are used here are re-exported as named types for convenience.
 */
export * from './createTankobonSalesBodyDto'
export * from './defenseDashboardResDtoOutput'
export * from './defenseDashboardResDtoOutputRankingTrendItem'
export * from './defenseDashboardResDtoOutputSerialization'
export * from './defenseDashboardResDtoOutputSeriesReportsItem'
export * from './defenseDashboardResDtoOutputTankobon'
export * from './defenseDashboardResDtoOutputTankobonVolumesItem'
export * from './tankobonControllerDashboardPathParameters'
export * from './tankobonSalesResDtoOutput'

