/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type {
  ConfirmStageOutputsBodyDto,
  CreateStageBodyDto,
  MessageResDtoOutput,
  ProductionStageControllerAddPathParameters,
  ProductionStageControllerCompletePathParameters,
  ProductionStageControllerConfirmOutputsPathParameters,
  ProductionStageControllerListPagesPathParameters,
  ProductionStageControllerListPathParameters,
  ProductionStageControllerPatchPathParameters,
  ProductionStageControllerRemovePathParameters,
  ProductionStageControllerReopenPathParameters,
  ProductionStageResDtoOutput,
  StageListResDtoOutput,
  StagePageListResDtoOutput,
  StageReopenResDtoOutput,
  UpdateStageBodyDto
} from '../../model/production-stages';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Danh sách giai đoạn sản xuất của chapter và analytics
 */
export type productionStageControllerListResponse200 = {
  data: StageListResDtoOutput
  status: 200
}
    
export type productionStageControllerListResponseSuccess = (productionStageControllerListResponse200) & {
  headers: Headers;
};
;

export type productionStageControllerListResponse = (productionStageControllerListResponseSuccess)

export const getProductionStageControllerListUrl = ({ id }: ProductionStageControllerListPathParameters,) => {


  

  return `/chapters/${id}/stages`
}

export const productionStageControllerList = async ({ id }: ProductionStageControllerListPathParameters, options?: RequestInit): Promise<productionStageControllerListResponse> => {
  
  return customFetch<productionStageControllerListResponse>(getProductionStageControllerListUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Chèn custom stage trong vùng chưa mở
 */
export type productionStageControllerAddResponse201 = {
  data: ProductionStageResDtoOutput
  status: 201
}
    
export type productionStageControllerAddResponseSuccess = (productionStageControllerAddResponse201) & {
  headers: Headers;
};
;

export type productionStageControllerAddResponse = (productionStageControllerAddResponseSuccess)

export const getProductionStageControllerAddUrl = ({ id }: ProductionStageControllerAddPathParameters,) => {


  

  return `/chapters/${id}/stages`
}

export const productionStageControllerAdd = async ({ id }: ProductionStageControllerAddPathParameters,
    createStageBodyDto: CreateStageBodyDto, options?: RequestInit): Promise<productionStageControllerAddResponse> => {
  
  return customFetch<productionStageControllerAddResponse>(getProductionStageControllerAddUrl({ id }),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createStageBodyDto,)
  }
);}


/**
 * @summary Hoàn thành stage ACTIVE và mở stage kế tiếp
 */
export type productionStageControllerCompleteResponse201 = {
  data: MessageResDtoOutput
  status: 201
}
    
export type productionStageControllerCompleteResponseSuccess = (productionStageControllerCompleteResponse201) & {
  headers: Headers;
};
;

export type productionStageControllerCompleteResponse = (productionStageControllerCompleteResponseSuccess)

export const getProductionStageControllerCompleteUrl = ({ id, stageId }: ProductionStageControllerCompletePathParameters,) => {


  

  return `/chapters/${id}/stages/${stageId}/complete`
}

export const productionStageControllerComplete = async ({ id, stageId }: ProductionStageControllerCompletePathParameters, options?: RequestInit): Promise<productionStageControllerCompleteResponse> => {
  
  return customFetch<productionStageControllerCompleteResponse>(getProductionStageControllerCompleteUrl({ id, stageId }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Mở lại stage COMPLETED khi Editor yêu cầu chỉnh sửa; các stage phía sau bị đưa về LOCKED
 */
export type productionStageControllerReopenResponse201 = {
  data: StageReopenResDtoOutput
  status: 201
}
    
export type productionStageControllerReopenResponseSuccess = (productionStageControllerReopenResponse201) & {
  headers: Headers;
};
;

export type productionStageControllerReopenResponse = (productionStageControllerReopenResponseSuccess)

export const getProductionStageControllerReopenUrl = ({ id, stageId }: ProductionStageControllerReopenPathParameters,) => {


  

  return `/chapters/${id}/stages/${stageId}/reopen`
}

export const productionStageControllerReopen = async ({ id, stageId }: ProductionStageControllerReopenPathParameters, options?: RequestInit): Promise<productionStageControllerReopenResponse> => {
  
  return customFetch<productionStageControllerReopenResponse>(getProductionStageControllerReopenUrl({ id, stageId }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Sửa tên hoặc deadline stage chưa hoàn thành
 */
export type productionStageControllerPatchResponse200 = {
  data: ProductionStageResDtoOutput
  status: 200
}
    
export type productionStageControllerPatchResponseSuccess = (productionStageControllerPatchResponse200) & {
  headers: Headers;
};
;

export type productionStageControllerPatchResponse = (productionStageControllerPatchResponseSuccess)

export const getProductionStageControllerPatchUrl = ({ id, stageId }: ProductionStageControllerPatchPathParameters,) => {


  

  return `/chapters/${id}/stages/${stageId}`
}

export const productionStageControllerPatch = async ({ id, stageId }: ProductionStageControllerPatchPathParameters,
    updateStageBodyDto: UpdateStageBodyDto, options?: RequestInit): Promise<productionStageControllerPatchResponse> => {
  
  return customFetch<productionStageControllerPatchResponse>(getProductionStageControllerPatchUrl({ id, stageId }),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateStageBodyDto,)
  }
);}


/**
 * @summary Xoá stage LOCKED chưa có task
 */
export type productionStageControllerRemoveResponse200 = {
  data: MessageResDtoOutput
  status: 200
}
    
export type productionStageControllerRemoveResponseSuccess = (productionStageControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type productionStageControllerRemoveResponse = (productionStageControllerRemoveResponseSuccess)

export const getProductionStageControllerRemoveUrl = ({ id, stageId }: ProductionStageControllerRemovePathParameters,) => {


  

  return `/chapters/${id}/stages/${stageId}`
}

export const productionStageControllerRemove = async ({ id, stageId }: ProductionStageControllerRemovePathParameters, options?: RequestInit): Promise<productionStageControllerRemoveResponse> => {
  
  return customFetch<productionStageControllerRemoveResponse>(getProductionStageControllerRemoveUrl({ id, stageId }),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * @summary Liệt kê immutable input/output snapshot của page trong stage
 */
export type productionStageControllerListPagesResponse200 = {
  data: StagePageListResDtoOutput
  status: 200
}
    
export type productionStageControllerListPagesResponseSuccess = (productionStageControllerListPagesResponse200) & {
  headers: Headers;
};
;

export type productionStageControllerListPagesResponse = (productionStageControllerListPagesResponseSuccess)

export const getProductionStageControllerListPagesUrl = ({ id, stageId }: ProductionStageControllerListPagesPathParameters,) => {


  

  return `/chapters/${id}/stages/${stageId}/pages`
}

export const productionStageControllerListPages = async ({ id, stageId }: ProductionStageControllerListPagesPathParameters, options?: RequestInit): Promise<productionStageControllerListPagesResponse> => {
  
  return customFetch<productionStageControllerListPagesResponse>(getProductionStageControllerListPagesUrl({ id, stageId }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Xác nhận output của toàn bộ page trong stage ACTIVE
 */
export type productionStageControllerConfirmOutputsResponse200 = {
  data: StagePageListResDtoOutput
  status: 200
}
    
export type productionStageControllerConfirmOutputsResponseSuccess = (productionStageControllerConfirmOutputsResponse200) & {
  headers: Headers;
};
;

export type productionStageControllerConfirmOutputsResponse = (productionStageControllerConfirmOutputsResponseSuccess)

export const getProductionStageControllerConfirmOutputsUrl = ({ id, stageId }: ProductionStageControllerConfirmOutputsPathParameters,) => {


  

  return `/chapters/${id}/stages/${stageId}/outputs`
}

export const productionStageControllerConfirmOutputs = async ({ id, stageId }: ProductionStageControllerConfirmOutputsPathParameters,
    confirmStageOutputsBodyDto: ConfirmStageOutputsBodyDto, options?: RequestInit): Promise<productionStageControllerConfirmOutputsResponse> => {
  
  return customFetch<productionStageControllerConfirmOutputsResponse>(getProductionStageControllerConfirmOutputsUrl({ id, stageId }),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      confirmStageOutputsBodyDto,)
  }
);}


