/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * The WDP API description
 * OpenAPI spec version: 1.0
 */
import type {
  CreateAssistantReviewBodyDto,
  CreateMangakaReviewBodyDto,
  ReviewListResDtoOutput,
  ReviewResDtoOutput,
  ReviewsControllerListAssistantReviewsParams,
  ReviewsControllerListMangakaReviewsParams
} from '../../model/reviews';

import { customFetch } from '../../mutator/custom-fetch';

export type reviewsControllerCreateAssistantReviewResponseDefault = {
  data: ReviewResDtoOutput
  status: number
}
    
;
export type reviewsControllerCreateAssistantReviewResponseError = (reviewsControllerCreateAssistantReviewResponseDefault) & {
  headers: Headers;
};

export type reviewsControllerCreateAssistantReviewResponse = (reviewsControllerCreateAssistantReviewResponseError)

export const getReviewsControllerCreateAssistantReviewUrl = () => {


  

  return `/assistant-reviews`
}

export const reviewsControllerCreateAssistantReview = async (createAssistantReviewBodyDto: CreateAssistantReviewBodyDto, options?: RequestInit): Promise<reviewsControllerCreateAssistantReviewResponse> => {
  
  return customFetch<reviewsControllerCreateAssistantReviewResponse>(getReviewsControllerCreateAssistantReviewUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createAssistantReviewBodyDto,)
  }
);}


export type reviewsControllerListAssistantReviewsResponseDefault = {
  data: ReviewListResDtoOutput
  status: number
}
    
;
export type reviewsControllerListAssistantReviewsResponseError = (reviewsControllerListAssistantReviewsResponseDefault) & {
  headers: Headers;
};

export type reviewsControllerListAssistantReviewsResponse = (reviewsControllerListAssistantReviewsResponseError)

export const getReviewsControllerListAssistantReviewsUrl = (params: ReviewsControllerListAssistantReviewsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/assistant-reviews?${stringifiedParams}` : `/assistant-reviews`
}

export const reviewsControllerListAssistantReviews = async (params: ReviewsControllerListAssistantReviewsParams, options?: RequestInit): Promise<reviewsControllerListAssistantReviewsResponse> => {
  
  return customFetch<reviewsControllerListAssistantReviewsResponse>(getReviewsControllerListAssistantReviewsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type reviewsControllerCreateMangakaReviewResponseDefault = {
  data: ReviewResDtoOutput
  status: number
}
    
;
export type reviewsControllerCreateMangakaReviewResponseError = (reviewsControllerCreateMangakaReviewResponseDefault) & {
  headers: Headers;
};

export type reviewsControllerCreateMangakaReviewResponse = (reviewsControllerCreateMangakaReviewResponseError)

export const getReviewsControllerCreateMangakaReviewUrl = () => {


  

  return `/mangaka-reviews`
}

export const reviewsControllerCreateMangakaReview = async (createMangakaReviewBodyDto: CreateMangakaReviewBodyDto, options?: RequestInit): Promise<reviewsControllerCreateMangakaReviewResponse> => {
  
  return customFetch<reviewsControllerCreateMangakaReviewResponse>(getReviewsControllerCreateMangakaReviewUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createMangakaReviewBodyDto,)
  }
);}


export type reviewsControllerListMangakaReviewsResponseDefault = {
  data: ReviewListResDtoOutput
  status: number
}
    
;
export type reviewsControllerListMangakaReviewsResponseError = (reviewsControllerListMangakaReviewsResponseDefault) & {
  headers: Headers;
};

export type reviewsControllerListMangakaReviewsResponse = (reviewsControllerListMangakaReviewsResponseError)

export const getReviewsControllerListMangakaReviewsUrl = (params: ReviewsControllerListMangakaReviewsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/mangaka-reviews?${stringifiedParams}` : `/mangaka-reviews`
}

export const reviewsControllerListMangakaReviews = async (params: ReviewsControllerListMangakaReviewsParams, options?: RequestInit): Promise<reviewsControllerListMangakaReviewsResponse> => {
  
  return customFetch<reviewsControllerListMangakaReviewsResponse>(getReviewsControllerListMangakaReviewsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


