/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type {
  AiControllerApplyJobPathParameters,
  AiControllerGetJobPathParameters,
  AiControllerListJobsParams,
  AiControllerListJobsPathParameters,
  AiControllerSegmentPathParameters,
  AiJobListResDtoOutput,
  AiJobResDtoOutput,
  ApplyAiJobResDtoOutput,
  SegmentAcceptedResDtoOutput,
  SegmentPageBodyDto
} from '../../model/ai';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Run async AI page segmentation and return a job id for polling
 */
export type aiControllerSegmentResponse201 = {
  data: SegmentAcceptedResDtoOutput
  status: 201
}
    
export type aiControllerSegmentResponseSuccess = (aiControllerSegmentResponse201) & {
  headers: Headers;
};
;

export type aiControllerSegmentResponse = (aiControllerSegmentResponseSuccess)

export const getAiControllerSegmentUrl = ({ id }: AiControllerSegmentPathParameters,) => {


  

  return `/pages/${id}/segment`
}

export const aiControllerSegment = async ({ id }: AiControllerSegmentPathParameters,
    segmentPageBodyDto: SegmentPageBodyDto, options?: RequestInit): Promise<aiControllerSegmentResponse> => {
  
  return customFetch<aiControllerSegmentResponse>(getAiControllerSegmentUrl({ id }),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      segmentPageBodyDto,)
  }
);}


/**
 * @summary Poll one AI job status and proposed regions
 */
export type aiControllerGetJobResponse200 = {
  data: AiJobResDtoOutput
  status: 200
}
    
export type aiControllerGetJobResponseSuccess = (aiControllerGetJobResponse200) & {
  headers: Headers;
};
;

export type aiControllerGetJobResponse = (aiControllerGetJobResponseSuccess)

export const getAiControllerGetJobUrl = ({ id }: AiControllerGetJobPathParameters,) => {


  

  return `/ai-jobs/${id}`
}

export const aiControllerGetJob = async ({ id }: AiControllerGetJobPathParameters, options?: RequestInit): Promise<aiControllerGetJobResponse> => {
  
  return customFetch<aiControllerGetJobResponse>(getAiControllerGetJobUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary List AI proposals for one page without proposedRegions payload
 */
export type aiControllerListJobsResponse200 = {
  data: AiJobListResDtoOutput
  status: 200
}
    
export type aiControllerListJobsResponseSuccess = (aiControllerListJobsResponse200) & {
  headers: Headers;
};
;

export type aiControllerListJobsResponse = (aiControllerListJobsResponseSuccess)

export const getAiControllerListJobsUrl = ({ id }: AiControllerListJobsPathParameters,
    params?: AiControllerListJobsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/pages/${id}/ai-jobs?${stringifiedParams}` : `/pages/${id}/ai-jobs`
}

export const aiControllerListJobs = async ({ id }: AiControllerListJobsPathParameters,
    params?: AiControllerListJobsParams, options?: RequestInit): Promise<aiControllerListJobsResponse> => {
  
  return customFetch<aiControllerListJobsResponse>(getAiControllerListJobsUrl({ id },params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Apply one AI proposal into Region[] while preserving manual/confirmed/task-linked regions
 */
export type aiControllerApplyJobResponse201 = {
  data: ApplyAiJobResDtoOutput
  status: 201
}
    
export type aiControllerApplyJobResponseSuccess = (aiControllerApplyJobResponse201) & {
  headers: Headers;
};
;

export type aiControllerApplyJobResponse = (aiControllerApplyJobResponseSuccess)

export const getAiControllerApplyJobUrl = ({ id }: AiControllerApplyJobPathParameters,) => {


  

  return `/ai-jobs/${id}/apply`
}

export const aiControllerApplyJob = async ({ id }: AiControllerApplyJobPathParameters, options?: RequestInit): Promise<aiControllerApplyJobResponse> => {
  
  return customFetch<aiControllerApplyJobResponse>(getAiControllerApplyJobUrl({ id }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


