/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * The WDP API description
 * OpenAPI spec version: 1.0
 */

export interface ChangePasswordBodyDto {
  /**
   * @minLength 6
   * @maxLength 100
   */
  currentPassword: string;
  /** @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,100}$ */
  newPassword: string;
  /**
   * @minLength 8
   * @maxLength 100
   */
  confirmNewPassword: string;
}
