/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { CreatePublicationVersionBodyDtoReadingDirection } from './createPublicationVersionBodyDtoReadingDirection';
import type { CreatePublicationVersionBodyDtoVersionType } from './createPublicationVersionBodyDtoVersionType';

export interface CreatePublicationVersionBodyDto {
  /**
   * Mã ngôn ngữ, vd JA/EN/VI
   * @minLength 1
   * @maxLength 20
   */
  language: string;
  /** Reading direction: RTL (right-to-left, manga gốc) | LTR (left-to-right, bản dịch phương Tây). Values: RTL, LTR */
  readingDirection?: CreatePublicationVersionBodyDtoReadingDirection;
  /**
   * ORIGINAL | DIGITAL | FLIPPED
   * @nullable
   */
  versionType?: CreatePublicationVersionBodyDtoVersionType;
  /**
   * @maxLength 2000
   * @nullable
   */
  notes?: string | null;
}
