/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { AnnotationListResDtoOutputItemsItemTargetType } from './annotationListResDtoOutputItemsItemTargetType';
import type { AnnotationListResDtoOutputItemsItemAnnotationType } from './annotationListResDtoOutputItemsItemAnnotationType';
import type { AnnotationListResDtoOutputItemsItemReviewStage } from './annotationListResDtoOutputItemsItemReviewStage';
import type { AnnotationListResDtoOutputItemsItemCoordinates } from './annotationListResDtoOutputItemsItemCoordinates';
import type { AnnotationListResDtoOutputItemsItemAuthor } from './annotationListResDtoOutputItemsItemAuthor';

export type AnnotationListResDtoOutputItemsItem = {
  id: string;
  /** @nullable */
  taskId: string | null;
  /** @nullable */
  authorId: string | null;
  /**
   * RoleCode của người tạo annotation: Allowed role codes: MANGAKA, ASSISTANT, EDITOR, BOARD_MEMBER, SUPER_ADMIN
   * @nullable
   */
  authorRole: string | null;
  /**
   * Annotation target: PAGE, REGION, TASK, MANUSCRIPT, NAME. Values: PAGE, REGION, TASK, MANUSCRIPT, NAME
   * @nullable
   */
  targetType: AnnotationListResDtoOutputItemsItemTargetType;
  /** @nullable */
  targetId: string | null;
  /**
   * Annotation type: TEXT, HIGHLIGHT, DRAWING. Values: TEXT, HIGHLIGHT, DRAWING
   * @nullable
   */
  annotationType: AnnotationListResDtoOutputItemsItemAnnotationType;
  /**
   * Review stage: ASSISTANT, MANGAKA, EDITOR. Values: ASSISTANT, MANGAKA, EDITOR
   * @nullable
   */
  reviewStage: AnnotationListResDtoOutputItemsItemReviewStage;
  /** @nullable */
  coordinates: AnnotationListResDtoOutputItemsItemCoordinates;
  /** @nullable */
  content: string | null;
  isResolved: boolean;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  /**
   * Người tạo annotation — có ở GET list/detail
   * @nullable
   */
  author?: AnnotationListResDtoOutputItemsItemAuthor;
};
