/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type {
  AdminDashboardResDtoOutput,
  AssistantDashboardResDtoOutput,
  BoardDashboardResDtoOutput,
  EditorDashboardResDtoOutput,
  MangakaDashboardResDtoOutput,
  MangakaEarningsResDtoOutput
} from '../../model/dashboard';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Dashboard Mangaka: studio + rankings + unread + openRevisions
 */
export type mangakaDashboardControllerMangakaResponse200 = {
  data: MangakaDashboardResDtoOutput
  status: 200
}
    
export type mangakaDashboardControllerMangakaResponseSuccess = (mangakaDashboardControllerMangakaResponse200) & {
  headers: Headers;
};
;

export type mangakaDashboardControllerMangakaResponse = (mangakaDashboardControllerMangakaResponseSuccess)

export const getMangakaDashboardControllerMangakaUrl = () => {


  

  return `/dashboard/mangaka`
}

export const mangakaDashboardControllerMangaka = async ( options?: RequestInit): Promise<mangakaDashboardControllerMangakaResponse> => {
  
  return customFetch<mangakaDashboardControllerMangakaResponse>(getMangakaDashboardControllerMangakaUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Thu nhập Mangaka (PaymentRecord tổng hợp)
 */
export type mangakaDashboardControllerEarningsResponse200 = {
  data: MangakaEarningsResDtoOutput
  status: 200
}
    
export type mangakaDashboardControllerEarningsResponseSuccess = (mangakaDashboardControllerEarningsResponse200) & {
  headers: Headers;
};
;

export type mangakaDashboardControllerEarningsResponse = (mangakaDashboardControllerEarningsResponseSuccess)

export const getMangakaDashboardControllerEarningsUrl = () => {


  

  return `/dashboard/mangaka/earnings`
}

export const mangakaDashboardControllerEarnings = async ( options?: RequestInit): Promise<mangakaDashboardControllerEarningsResponse> => {
  
  return customFetch<mangakaDashboardControllerEarningsResponse>(getMangakaDashboardControllerEarningsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Dashboard Assistant: workload + assignments + reputation
 */
export type assistantDashboardControllerAssistantResponse200 = {
  data: AssistantDashboardResDtoOutput
  status: 200
}
    
export type assistantDashboardControllerAssistantResponseSuccess = (assistantDashboardControllerAssistantResponse200) & {
  headers: Headers;
};
;

export type assistantDashboardControllerAssistantResponse = (assistantDashboardControllerAssistantResponseSuccess)

export const getAssistantDashboardControllerAssistantUrl = () => {


  

  return `/dashboard/assistant`
}

export const assistantDashboardControllerAssistant = async ( options?: RequestInit): Promise<assistantDashboardControllerAssistantResponse> => {
  
  return customFetch<assistantDashboardControllerAssistantResponse>(getAssistantDashboardControllerAssistantUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Dashboard Editor: series overview + review queue + at-risk + production alerts + pending contracts
 */
export type editorDashboardControllerEditorResponse200 = {
  data: EditorDashboardResDtoOutput
  status: 200
}
    
export type editorDashboardControllerEditorResponseSuccess = (editorDashboardControllerEditorResponse200) & {
  headers: Headers;
};
;

export type editorDashboardControllerEditorResponse = (editorDashboardControllerEditorResponseSuccess)

export const getEditorDashboardControllerEditorUrl = () => {


  

  return `/dashboard/editor`
}

export const editorDashboardControllerEditor = async ( options?: RequestInit): Promise<editorDashboardControllerEditorResponse> => {
  
  return customFetch<editorDashboardControllerEditorResponse>(getEditorDashboardControllerEditorUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Dashboard Board: pending decisions + upcoming sessions + at-risk severe
 */
export type boardDashboardControllerBoardResponse200 = {
  data: BoardDashboardResDtoOutput
  status: 200
}
    
export type boardDashboardControllerBoardResponseSuccess = (boardDashboardControllerBoardResponse200) & {
  headers: Headers;
};
;

export type boardDashboardControllerBoardResponse = (boardDashboardControllerBoardResponseSuccess)

export const getBoardDashboardControllerBoardUrl = () => {


  

  return `/dashboard/board`
}

export const boardDashboardControllerBoard = async ( options?: RequestInit): Promise<boardDashboardControllerBoardResponse> => {
  
  return customFetch<boardDashboardControllerBoardResponse>(getBoardDashboardControllerBoardUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Dashboard Admin: system stats + unread
 */
export type adminDashboardControllerAdminResponse200 = {
  data: AdminDashboardResDtoOutput
  status: 200
}
    
export type adminDashboardControllerAdminResponseSuccess = (adminDashboardControllerAdminResponse200) & {
  headers: Headers;
};
;

export type adminDashboardControllerAdminResponse = (adminDashboardControllerAdminResponseSuccess)

export const getAdminDashboardControllerAdminUrl = () => {


  

  return `/dashboard/admin`
}

export const adminDashboardControllerAdmin = async ( options?: RequestInit): Promise<adminDashboardControllerAdminResponse> => {
  
  return customFetch<adminDashboardControllerAdminResponse>(getAdminDashboardControllerAdminUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


