/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type {
  AuditControllerListParams,
  AuditLogListResDtoOutput
} from '../../model/audit';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary List audit logs for privileged audit viewers
 */
export type auditControllerListResponse200 = {
  data: AuditLogListResDtoOutput
  status: 200
}

export type auditControllerListResponse422 = {
  data: void
  status: 422
}
    
export type auditControllerListResponseSuccess = (auditControllerListResponse200) & {
  headers: Headers;
};
export type auditControllerListResponseError = (auditControllerListResponse422) & {
  headers: Headers;
};

export type auditControllerListResponse = (auditControllerListResponseSuccess | auditControllerListResponseError)

export const getAuditControllerListUrl = (params?: AuditControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/audit?${stringifiedParams}` : `/audit`
}

export const auditControllerList = async (params?: AuditControllerListParams, options?: RequestInit): Promise<auditControllerListResponse> => {
  
  return customFetch<auditControllerListResponse>(getAuditControllerListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


