/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AuditLogListResDtoOutput
} from '../../model/audit';


export const getAuditControllerListResponseMock = (overrideResponse: Partial< AuditLogListResDtoOutput > = {}): AuditLogListResDtoOutput => ({items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), actorId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), entityType: faker.helpers.arrayElement(['SERIES','MANUSCRIPT','PAGE','CHAPTER','TASK','DEADLINE_REQUEST','USER','REGION','APP_CONFIG','CONTRACT','BOARD_DECISION','REPRINT_REQUEST','TRANSFER_REQUEST','PAYMENT_RECORD','SURVEY_PERIOD','PUBLICATION_VERSION','BOARD_SESSION'] as const), entityId: faker.string.alpha({length: {min: 10, max: 20}}), action: faker.string.alpha({length: {min: 10, max: 20}}), fromState: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), toState: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reason: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), createdAt: faker.string.alpha({length: {min: 10, max: 20}})})), total: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), limit: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), offset: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ...overrideResponse})


export const getAuditControllerListMockHandler = (overrideResponse?: AuditLogListResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AuditLogListResDtoOutput> | AuditLogListResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/audit', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAuditControllerListResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getAuditMock = () => [
  getAuditControllerListMockHandler()
]
