/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */

export interface PatchAppConfigBodyDto {
  /**
   * Grace days for co-owner approval flows
   * @minimum 0
   * @maximum 9007199254740991
   * @nullable
   */
  coOwnerApprovalGraceDays?: number | null;
  /**
   * Maximum name review rounds before loop warning
   * @maximum 9007199254740991
   * @nullable
   */
  nameMaxReviewRounds?: number | null;
  /**
   * Minimum reputation score for recommendations
   * @minimum 1
   * @maximum 5
   * @nullable
   */
  reputationRecommendThreshold?: number | null;
  /**
   * Days before a hiatus is considered too long
   * @maximum 9007199254740991
   * @nullable
   */
  hiatusTooLongDays?: number | null;
  /**
   * Vote count below which reliability is low
   * @minimum 0
   * @maximum 9007199254740991
   * @nullable
   */
  lowVoteReliabilityThreshold?: number | null;
  /**
   * Maximum upload size in bytes; hard cap is 50MB
   * @maximum 52428800
   * @nullable
   */
  maxUploadBytes?: number | null;
  /**
   * Grace days around assignment lifecycle checks
   * @minimum 0
   * @maximum 9007199254740991
   * @nullable
   */
  assignmentGraceDays?: number | null;
}
