/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * The WDP API description
 * OpenAPI spec version: 1.0
 */

export type ReviewsControllerListMangakaReviewsParams = {
/**
 * @minLength 1
 */
mangakaId: string;
/**
 * @minimum 0
 * @maximum 9007199254740991
 * @exclusiveMinimum
 */
limit?: number;
/**
 * @minimum 0
 * @maximum 9007199254740991
 */
offset?: number;
};
