/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * The WDP API description
 * OpenAPI spec version: 1.0
 */

export type AdminCreateUserBodyDtoRoleCode = typeof AdminCreateUserBodyDtoRoleCode[keyof typeof AdminCreateUserBodyDtoRoleCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminCreateUserBodyDtoRoleCode = {
  EDITOR: 'EDITOR',
  BOARD_MEMBER: 'BOARD_MEMBER',
} as const;
