/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * The WDP API description
 * OpenAPI spec version: 1.0
 */
import type { AdminCreateUserBodyDtoRoleCode } from './adminCreateUserBodyDtoRoleCode';

export interface AdminCreateUserBodyDto {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /**
   * @minLength 9
   * @maxLength 15
   */
  phoneNumber: string;
  roleCode: AdminCreateUserBodyDtoRoleCode;
}
