/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * The WDP API description
 * OpenAPI spec version: 1.0
 */

export type AssistantProfileResDtoOutputSpecializationsItem = typeof AssistantProfileResDtoOutputSpecializationsItem[keyof typeof AssistantProfileResDtoOutputSpecializationsItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssistantProfileResDtoOutputSpecializationsItem = {
  BACKGROUND: 'BACKGROUND',
  SCREENTONE: 'SCREENTONE',
  EFFECT_LINES: 'EFFECT_LINES',
  INKING: 'INKING',
  COLORING: 'COLORING',
  LETTERING: 'LETTERING',
} as const;
