/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * The WDP API description
 * OpenAPI spec version: 1.0
 */

export type AssistantProfileBodyDtoAvailabilityStatus = typeof AssistantProfileBodyDtoAvailabilityStatus[keyof typeof AssistantProfileBodyDtoAvailabilityStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssistantProfileBodyDtoAvailabilityStatus = {
  AVAILABLE: 'AVAILABLE',
  BUSY: 'BUSY',
  ON_LEAVE: 'ON_LEAVE',
  UNAVAILABLE: 'UNAVAILABLE',
} as const;
