/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * The WDP API description
 * OpenAPI spec version: 1.0
 */

export interface MangakaProfileBodyDto {
  /**
   * @minLength 1
   * @maxLength 100
   */
  penName: string;
  genres?: string[];
  experienceLevel?: string;
  bio?: string;
  portfolioFiles?: string[];
}
