/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */

/**
 * Board decision type: CONTINUE, CANCEL, HIATUS, ENDING_ALLOWANCE, SERIES_CONTRACT_APPROVAL, SERIALIZATION, CANCELLATION, FORMAT_CHANGE, COMPLETION, REPRINT, TRANSFER, CONTRACT, OTHER. Values: CONTINUE, CANCEL, HIATUS, ENDING_ALLOWANCE, SERIES_CONTRACT_APPROVAL, SERIALIZATION, CANCELLATION, FORMAT_CHANGE, COMPLETION, REPRINT, TRANSFER, CONTRACT
 */
export type CreateBoardDecisionBodyDtoDecisionType = typeof CreateBoardDecisionBodyDtoDecisionType[keyof typeof CreateBoardDecisionBodyDtoDecisionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateBoardDecisionBodyDtoDecisionType = {
  CONTINUE: 'CONTINUE',
  CANCEL: 'CANCEL',
  HIATUS: 'HIATUS',
  ENDING_ALLOWANCE: 'ENDING_ALLOWANCE',
  SERIES_CONTRACT_APPROVAL: 'SERIES_CONTRACT_APPROVAL',
  SERIALIZATION: 'SERIALIZATION',
  CANCELLATION: 'CANCELLATION',
  FORMAT_CHANGE: 'FORMAT_CHANGE',
  COMPLETION: 'COMPLETION',
  REPRINT: 'REPRINT',
  TRANSFER: 'TRANSFER',
  CONTRACT: 'CONTRACT',
} as const;
