/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { DeadlineRequestResDtoOutputStatus } from './deadlineRequestResDtoOutputStatus';

export interface DeadlineRequestResDtoOutput {
  id: string;
  scheduleId: string;
  /** @nullable */
  chapterId: string | null;
  /** @nullable */
  seriesId: string | null;
  /**
   * Phe khởi tạo: 'MANGAKA' | 'EDITOR'
   * @nullable
   */
  requestedBy: string | null;
  /**
   * Phe đề xuất gần nhất
   * @nullable
   */
  lastProposedBy: string | null;
  /** @nullable */
  currentDeadline: string | null;
  /** @nullable */
  requestedDeadline: string | null;
  /** @nullable */
  reason: string | null;
  affectsSlot: boolean;
  /** Deadline negotiation status: PROPOSED, COUNTER_PROPOSED, AGREED_BY_PARTIES, APPROVED, REJECTED, ESCALATED, BOARD_REVIEW. Values: PROPOSED, COUNTER_PROPOSED, AGREED_BY_PARTIES, BOARD_REVIEW, ESCALATED, APPROVED, REJECTED */
  status: DeadlineRequestResDtoOutputStatus;
  /** @nullable */
  boardReviewedBy: string | null;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
}
