/**
 * Auto-generated barrel for the revision tag.
 * Regenerated by scripts/organize-models-by-tag.mjs after each orval run.
 *
 * Local files are exported directly. Types that belong to OTHER tags
 * but are used here are re-exported as named types for convenience.
 */
export * from './revisionControllerListIsResolved'
export * from './revisionControllerListParams'
export * from './revisionControllerListTargetType'
export * from './revisionControllerResolvePathParameters'
export * from './revisionRequestListResDtoOutput'
export * from './revisionRequestListResDtoOutputItemsItem'
export * from './revisionRequestListResDtoOutputItemsItemRecipient'
export * from './revisionRequestListResDtoOutputItemsItemRequester'
export * from './revisionRequestListResDtoOutputItemsItemSeries'
export * from './revisionRequestListResDtoOutputItemsItemTargetType'
export * from './revisionRequestResDtoOutput'
export * from './revisionRequestResDtoOutputRecipient'
export * from './revisionRequestResDtoOutputRequester'
export * from './revisionRequestResDtoOutputSeries'
export * from './revisionRequestResDtoOutputTargetType'

