/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * The WDP API description
 * OpenAPI spec version: 1.0
 */
import type { SignUploadBodyDtoContentType } from './signUploadBodyDtoContentType';
import type { SignUploadBodyDtoAssetType } from './signUploadBodyDtoAssetType';

export interface SignUploadBodyDto {
  /**
   * @minLength 1
   * @maxLength 255
   */
  fileName: string;
  contentType: SignUploadBodyDtoContentType;
  /**
   * @minimum 0
   * @maximum 15728640
   * @exclusiveMinimum
   */
  contentLength: number;
  assetType?: SignUploadBodyDtoAssetType;
}
