/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type {
  AssignmentListResDtoOutput,
  AssignmentResDtoOutput,
  CreateInviteBodyDto,
  InviteListResDtoOutput,
  InviteResDtoOutput,
  StudioControllerAcceptInvitePathParameters,
  StudioControllerCancelInvitePathParameters,
  StudioControllerDeclineInvitePathParameters,
  StudioControllerGetAssignmentPathParameters,
  StudioControllerGetInvitePathParameters,
  StudioControllerListAssignmentsParams,
  StudioControllerListInvitesParams,
  StudioControllerTerminateAssignmentPathParameters,
  StudioOverviewResDtoOutput,
  TerminateAssignmentBodyDto
} from '../../model/studio';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Mangaka mời Assistant cộng tác → invite PENDING + notify
 */
export type studioControllerCreateInviteResponse201 = {
  data: InviteResDtoOutput
  status: 201
}
    
export type studioControllerCreateInviteResponseSuccess = (studioControllerCreateInviteResponse201) & {
  headers: Headers;
};
;

export type studioControllerCreateInviteResponse = (studioControllerCreateInviteResponseSuccess)

export const getStudioControllerCreateInviteUrl = () => {


  

  return `/collaboration-invites`
}

export const studioControllerCreateInvite = async (createInviteBodyDto: CreateInviteBodyDto, options?: RequestInit): Promise<studioControllerCreateInviteResponse> => {
  
  return customFetch<studioControllerCreateInviteResponse>(getStudioControllerCreateInviteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createInviteBodyDto,)
  }
);}


/**
 * @summary Danh sách invite theo scope role (Mangaka=gửi, Assistant=nhận)
 */
export type studioControllerListInvitesResponse200 = {
  data: InviteListResDtoOutput
  status: 200
}
    
export type studioControllerListInvitesResponseSuccess = (studioControllerListInvitesResponse200) & {
  headers: Headers;
};
;

export type studioControllerListInvitesResponse = (studioControllerListInvitesResponseSuccess)

export const getStudioControllerListInvitesUrl = (params?: StudioControllerListInvitesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collaboration-invites?${stringifiedParams}` : `/collaboration-invites`
}

export const studioControllerListInvites = async (params?: StudioControllerListInvitesParams, options?: RequestInit): Promise<studioControllerListInvitesResponse> => {
  
  return customFetch<studioControllerListInvitesResponse>(getStudioControllerListInvitesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Chi tiết 1 invite (chỉ owner hoặc invitee)
 */
export type studioControllerGetInviteResponse200 = {
  data: InviteResDtoOutput
  status: 200
}
    
export type studioControllerGetInviteResponseSuccess = (studioControllerGetInviteResponse200) & {
  headers: Headers;
};
;

export type studioControllerGetInviteResponse = (studioControllerGetInviteResponseSuccess)

export const getStudioControllerGetInviteUrl = ({ id }: StudioControllerGetInvitePathParameters,) => {


  

  return `/collaboration-invites/${id}`
}

export const studioControllerGetInvite = async ({ id }: StudioControllerGetInvitePathParameters, options?: RequestInit): Promise<studioControllerGetInviteResponse> => {
  
  return customFetch<studioControllerGetInviteResponse>(getStudioControllerGetInviteUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Assistant chấp nhận invite → tạo StudioAssignment ACTIVE
 */
export type studioControllerAcceptInviteResponse201 = {
  data: AssignmentResDtoOutput
  status: 201
}
    
export type studioControllerAcceptInviteResponseSuccess = (studioControllerAcceptInviteResponse201) & {
  headers: Headers;
};
;

export type studioControllerAcceptInviteResponse = (studioControllerAcceptInviteResponseSuccess)

export const getStudioControllerAcceptInviteUrl = ({ id }: StudioControllerAcceptInvitePathParameters,) => {


  

  return `/collaboration-invites/${id}/accept`
}

export const studioControllerAcceptInvite = async ({ id }: StudioControllerAcceptInvitePathParameters, options?: RequestInit): Promise<studioControllerAcceptInviteResponse> => {
  
  return customFetch<studioControllerAcceptInviteResponse>(getStudioControllerAcceptInviteUrl({ id }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Assistant từ chối invite → DECLINED
 */
export type studioControllerDeclineInviteResponse201 = {
  data: InviteResDtoOutput
  status: 201
}
    
export type studioControllerDeclineInviteResponseSuccess = (studioControllerDeclineInviteResponse201) & {
  headers: Headers;
};
;

export type studioControllerDeclineInviteResponse = (studioControllerDeclineInviteResponseSuccess)

export const getStudioControllerDeclineInviteUrl = ({ id }: StudioControllerDeclineInvitePathParameters,) => {


  

  return `/collaboration-invites/${id}/decline`
}

export const studioControllerDeclineInvite = async ({ id }: StudioControllerDeclineInvitePathParameters, options?: RequestInit): Promise<studioControllerDeclineInviteResponse> => {
  
  return customFetch<studioControllerDeclineInviteResponse>(getStudioControllerDeclineInviteUrl({ id }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Mangaka huỷ invite của mình → CANCELLED
 */
export type studioControllerCancelInviteResponse201 = {
  data: InviteResDtoOutput
  status: 201
}
    
export type studioControllerCancelInviteResponseSuccess = (studioControllerCancelInviteResponse201) & {
  headers: Headers;
};
;

export type studioControllerCancelInviteResponse = (studioControllerCancelInviteResponseSuccess)

export const getStudioControllerCancelInviteUrl = ({ id }: StudioControllerCancelInvitePathParameters,) => {


  

  return `/collaboration-invites/${id}/cancel`
}

export const studioControllerCancelInvite = async ({ id }: StudioControllerCancelInvitePathParameters, options?: RequestInit): Promise<studioControllerCancelInviteResponse> => {
  
  return customFetch<studioControllerCancelInviteResponse>(getStudioControllerCancelInviteUrl({ id }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Danh sách assignment theo scope role (filter status / activeNow=true)
 */
export type studioControllerListAssignmentsResponse200 = {
  data: AssignmentListResDtoOutput
  status: 200
}
    
export type studioControllerListAssignmentsResponseSuccess = (studioControllerListAssignmentsResponse200) & {
  headers: Headers;
};
;

export type studioControllerListAssignmentsResponse = (studioControllerListAssignmentsResponseSuccess)

export const getStudioControllerListAssignmentsUrl = (params?: StudioControllerListAssignmentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/studio-assignments?${stringifiedParams}` : `/studio-assignments`
}

export const studioControllerListAssignments = async (params?: StudioControllerListAssignmentsParams, options?: RequestInit): Promise<studioControllerListAssignmentsResponse> => {
  
  return customFetch<studioControllerListAssignmentsResponse>(getStudioControllerListAssignmentsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Chi tiết 1 assignment (chỉ mangaka owner hoặc assistant)
 */
export type studioControllerGetAssignmentResponse200 = {
  data: AssignmentResDtoOutput
  status: 200
}
    
export type studioControllerGetAssignmentResponseSuccess = (studioControllerGetAssignmentResponse200) & {
  headers: Headers;
};
;

export type studioControllerGetAssignmentResponse = (studioControllerGetAssignmentResponseSuccess)

export const getStudioControllerGetAssignmentUrl = ({ id }: StudioControllerGetAssignmentPathParameters,) => {


  

  return `/studio-assignments/${id}`
}

export const studioControllerGetAssignment = async ({ id }: StudioControllerGetAssignmentPathParameters, options?: RequestInit): Promise<studioControllerGetAssignmentResponse> => {
  
  return customFetch<studioControllerGetAssignmentResponse>(getStudioControllerGetAssignmentUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Mangaka kết thúc sớm assignment ACTIVE → TERMINATED + notify
 */
export type studioControllerTerminateAssignmentResponse201 = {
  data: AssignmentResDtoOutput
  status: 201
}

export type studioControllerTerminateAssignmentResponse422 = {
  data: void
  status: 422
}
    
export type studioControllerTerminateAssignmentResponseSuccess = (studioControllerTerminateAssignmentResponse201) & {
  headers: Headers;
};
export type studioControllerTerminateAssignmentResponseError = (studioControllerTerminateAssignmentResponse422) & {
  headers: Headers;
};

export type studioControllerTerminateAssignmentResponse = (studioControllerTerminateAssignmentResponseSuccess | studioControllerTerminateAssignmentResponseError)

export const getStudioControllerTerminateAssignmentUrl = ({ id }: StudioControllerTerminateAssignmentPathParameters,) => {


  

  return `/studio-assignments/${id}/terminate`
}

export const studioControllerTerminateAssignment = async ({ id }: StudioControllerTerminateAssignmentPathParameters,
    terminateAssignmentBodyDto: TerminateAssignmentBodyDto, options?: RequestInit): Promise<studioControllerTerminateAssignmentResponse> => {
  
  return customFetch<studioControllerTerminateAssignmentResponse>(getStudioControllerTerminateAssignmentUrl({ id }),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      terminateAssignmentBodyDto,)
  }
);}


/**
 * @summary Mangaka overview of active production chapters sorted by warning severity
 */
export type studioOverviewControllerOverviewResponse200 = {
  data: StudioOverviewResDtoOutput
  status: 200
}
    
export type studioOverviewControllerOverviewResponseSuccess = (studioOverviewControllerOverviewResponse200) & {
  headers: Headers;
};
;

export type studioOverviewControllerOverviewResponse = (studioOverviewControllerOverviewResponseSuccess)

export const getStudioOverviewControllerOverviewUrl = () => {


  

  return `/studio/overview`
}

export const studioOverviewControllerOverview = async ( options?: RequestInit): Promise<studioOverviewControllerOverviewResponse> => {
  
  return customFetch<studioOverviewControllerOverviewResponse>(getStudioOverviewControllerOverviewUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


