/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  BoardConfigResDtoOutput,
  BoardDecisionResDtoOutput,
  BoardSessionResDtoOutput,
  BoardVoteResDtoOutput,
  MessageResDtoOutput,
  SeriesReportResDtoOutput
} from '../../model/board';


export const getBoardControllerCreateSessionResponseMock = (overrideResponse: Partial< BoardSessionResDtoOutput > = {}): BoardSessionResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), creatorId: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(['UPCOMING','ACTIVE','CONCLUDED'] as const), allowedEditorIds: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), startTime: {}, createdAt: {}, updatedAt: {}, ...overrideResponse})

export const getBoardControllerGetSessionsResponseMock = (): BoardSessionResDtoOutput[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), creatorId: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(['UPCOMING','ACTIVE','CONCLUDED'] as const), allowedEditorIds: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), startTime: {}, createdAt: {}, updatedAt: {}})))

export const getBoardControllerGetSessionByIdResponseMock = (overrideResponse: Partial< BoardSessionResDtoOutput > = {}): BoardSessionResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), creatorId: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(['UPCOMING','ACTIVE','CONCLUDED'] as const), allowedEditorIds: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), startTime: {}, createdAt: {}, updatedAt: {}, ...overrideResponse})

export const getBoardControllerStartSessionResponseMock = (overrideResponse: Partial< BoardSessionResDtoOutput > = {}): BoardSessionResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), creatorId: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(['UPCOMING','ACTIVE','CONCLUDED'] as const), allowedEditorIds: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), startTime: {}, createdAt: {}, updatedAt: {}, ...overrideResponse})

export const getBoardControllerGetConfigResponseMock = (overrideResponse: Partial< BoardConfigResDtoOutput > = {}): BoardConfigResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), updatedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), boardTotalMembers: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), quorumMin: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), approveMajorityRatio: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), isDefault: faker.datatype.boolean(), updatedAt: {}, ...overrideResponse})

export const getBoardControllerCreateDecisionResponseMock = (overrideResponse: Partial< BoardDecisionResDtoOutput > = {}): BoardDecisionResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), targetSeriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), boardSessionId: faker.string.alpha({length: {min: 10, max: 20}}), decisionType: faker.helpers.arrayElement([faker.helpers.arrayElement(['CONTINUE','CANCEL','HIATUS','ENDING_ALLOWANCE','SERIES_CONTRACT_APPROVAL','SERIALIZATION','CANCELLATION','FORMAT_CHANGE','COMPLETION','REPRINT','TRANSFER','CONTRACT'] as const), null]), result: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), totalVotes: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), approveCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), rejectCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), quorumMet: faker.datatype.boolean(), endingChapterAllowance: faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), null]), details: {}, decidedAt: {}, allowedEditorIds: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), votes: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({voterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), voteValue: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), note: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), votedAt: {}})), createdAt: {}, ...overrideResponse})

export const getBoardControllerGetDecisionsResponseMock = (): BoardDecisionResDtoOutput[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), targetSeriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), boardSessionId: faker.string.alpha({length: {min: 10, max: 20}}), decisionType: faker.helpers.arrayElement([faker.helpers.arrayElement(['CONTINUE','CANCEL','HIATUS','ENDING_ALLOWANCE','SERIES_CONTRACT_APPROVAL','SERIALIZATION','CANCELLATION','FORMAT_CHANGE','COMPLETION','REPRINT','TRANSFER','CONTRACT'] as const), null]), result: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), totalVotes: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), approveCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), rejectCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), quorumMet: faker.datatype.boolean(), endingChapterAllowance: faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), null]), details: {}, decidedAt: {}, allowedEditorIds: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), votes: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({voterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), voteValue: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), note: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), votedAt: {}})), createdAt: {}})))

export const getBoardControllerGetDecisionDetailsResponseMock = (overrideResponse: Partial< BoardDecisionResDtoOutput > = {}): BoardDecisionResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), targetSeriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), boardSessionId: faker.string.alpha({length: {min: 10, max: 20}}), decisionType: faker.helpers.arrayElement([faker.helpers.arrayElement(['CONTINUE','CANCEL','HIATUS','ENDING_ALLOWANCE','SERIES_CONTRACT_APPROVAL','SERIALIZATION','CANCELLATION','FORMAT_CHANGE','COMPLETION','REPRINT','TRANSFER','CONTRACT'] as const), null]), result: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), totalVotes: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), approveCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), rejectCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), quorumMet: faker.datatype.boolean(), endingChapterAllowance: faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), null]), details: {}, decidedAt: {}, allowedEditorIds: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), votes: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({voterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), voteValue: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), note: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), votedAt: {}})), createdAt: {}, ...overrideResponse})

export const getBoardControllerGetDecisionVotesResponseMock = (): BoardVoteResDtoOutput[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({voterId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), voteValue: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), note: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), votedAt: {}})))

export const getBoardControllerCastVoteResponseMock = (overrideResponse: Partial< MessageResDtoOutput > = {}): MessageResDtoOutput => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getBoardControllerGetReportsResponseMock = (): SeriesReportResDtoOutput[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), seriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), boardDecisionId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), preparedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reportType: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), content: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), attachments: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), createdAt: {}})))

export const getBoardControllerCreateSeriesReportResponseMock = (overrideResponse: Partial< SeriesReportResDtoOutput > = {}): SeriesReportResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), seriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), boardDecisionId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), preparedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reportType: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), content: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), attachments: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), createdAt: {}, ...overrideResponse})

export const getBoardControllerGetReportByIdResponseMock = (overrideResponse: Partial< SeriesReportResDtoOutput > = {}): SeriesReportResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), seriesId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), boardDecisionId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), preparedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reportType: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), content: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), attachments: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), createdAt: {}, ...overrideResponse})

export const getBoardControllerUpdateConfigResponseMock = (overrideResponse: Partial< BoardConfigResDtoOutput > = {}): BoardConfigResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), updatedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), boardTotalMembers: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), quorumMin: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), approveMajorityRatio: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), isDefault: faker.datatype.boolean(), updatedAt: {}, ...overrideResponse})


export const getBoardControllerCreateSessionMockHandler = (overrideResponse?: BoardSessionResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<BoardSessionResDtoOutput> | BoardSessionResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/board/sessions', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerCreateSessionResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerGetSessionsMockHandler = (overrideResponse?: BoardSessionResDtoOutput[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BoardSessionResDtoOutput[]> | BoardSessionResDtoOutput[]), options?: RequestHandlerOptions) => {
  return http.get('*/board/sessions', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerGetSessionsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerGetSessionByIdMockHandler = (overrideResponse?: BoardSessionResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BoardSessionResDtoOutput> | BoardSessionResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/board/sessions/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerGetSessionByIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerStartSessionMockHandler = (overrideResponse?: BoardSessionResDtoOutput | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<BoardSessionResDtoOutput> | BoardSessionResDtoOutput), options?: RequestHandlerOptions) => {
  return http.patch('*/board/sessions/:id/start', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerStartSessionResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerGetConfigMockHandler = (overrideResponse?: BoardConfigResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BoardConfigResDtoOutput> | BoardConfigResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/board/config', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerGetConfigResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerCreateDecisionMockHandler = (overrideResponse?: BoardDecisionResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<BoardDecisionResDtoOutput> | BoardDecisionResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/board/decisions', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerCreateDecisionResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerGetDecisionsMockHandler = (overrideResponse?: BoardDecisionResDtoOutput[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BoardDecisionResDtoOutput[]> | BoardDecisionResDtoOutput[]), options?: RequestHandlerOptions) => {
  return http.get('*/board/decisions', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerGetDecisionsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerGetDecisionDetailsMockHandler = (overrideResponse?: BoardDecisionResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BoardDecisionResDtoOutput> | BoardDecisionResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/board/decisions/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerGetDecisionDetailsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerGetDecisionVotesMockHandler = (overrideResponse?: BoardVoteResDtoOutput[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BoardVoteResDtoOutput[]> | BoardVoteResDtoOutput[]), options?: RequestHandlerOptions) => {
  return http.get('*/board/decisions/:id/votes', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerGetDecisionVotesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerCastVoteMockHandler = (overrideResponse?: MessageResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<MessageResDtoOutput> | MessageResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/board/decisions/:id/vote', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerCastVoteResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerGetReportsMockHandler = (overrideResponse?: SeriesReportResDtoOutput[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SeriesReportResDtoOutput[]> | SeriesReportResDtoOutput[]), options?: RequestHandlerOptions) => {
  return http.get('*/board/reports', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerGetReportsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerCreateSeriesReportMockHandler = (overrideResponse?: SeriesReportResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SeriesReportResDtoOutput> | SeriesReportResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/board/reports', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerCreateSeriesReportResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerGetReportByIdMockHandler = (overrideResponse?: SeriesReportResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SeriesReportResDtoOutput> | SeriesReportResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/board/reports/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerGetReportByIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getBoardControllerUpdateConfigMockHandler = (overrideResponse?: BoardConfigResDtoOutput | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<BoardConfigResDtoOutput> | BoardConfigResDtoOutput), options?: RequestHandlerOptions) => {
  return http.patch('*/board/config/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getBoardControllerUpdateConfigResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getBoardMock = () => [
  getBoardControllerCreateSessionMockHandler(),
  getBoardControllerGetSessionsMockHandler(),
  getBoardControllerGetSessionByIdMockHandler(),
  getBoardControllerStartSessionMockHandler(),
  getBoardControllerGetConfigMockHandler(),
  getBoardControllerCreateDecisionMockHandler(),
  getBoardControllerGetDecisionsMockHandler(),
  getBoardControllerGetDecisionDetailsMockHandler(),
  getBoardControllerGetDecisionVotesMockHandler(),
  getBoardControllerCastVoteMockHandler(),
  getBoardControllerGetReportsMockHandler(),
  getBoardControllerCreateSeriesReportMockHandler(),
  getBoardControllerGetReportByIdMockHandler(),
  getBoardControllerUpdateConfigMockHandler()
]
