/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type {
  BoardConfigResDtoOutput,
  BoardControllerCastVotePathParameters,
  BoardControllerGetDecisionDetailsPathParameters,
  BoardControllerGetDecisionVotesPathParameters,
  BoardControllerGetReportByIdPathParameters,
  BoardControllerGetSessionByIdPathParameters,
  BoardControllerStartSessionPathParameters,
  BoardControllerUpdateConfigPathParameters,
  BoardDecisionResDtoOutput,
  BoardSessionResDtoOutput,
  BoardVoteResDtoOutput,
  CastVoteBodyDto,
  CreateBoardDecisionBodyDto,
  CreateBoardSessionBodyDto,
  CreateSeriesReportBodyDto,
  MessageResDtoOutput,
  SeriesReportResDtoOutput,
  UpdateBoardConfigBodyDto
} from '../../model/board';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Editor tạo phiên họp Hội đồng → SCHEDULED
 */
export type boardControllerCreateSessionResponse201 = {
  data: BoardSessionResDtoOutput
  status: 201
}
    
export type boardControllerCreateSessionResponseSuccess = (boardControllerCreateSessionResponse201) & {
  headers: Headers;
};
;

export type boardControllerCreateSessionResponse = (boardControllerCreateSessionResponseSuccess)

export const getBoardControllerCreateSessionUrl = () => {


  

  return `/board/sessions`
}

export const boardControllerCreateSession = async (createBoardSessionBodyDto: CreateBoardSessionBodyDto, options?: RequestInit): Promise<boardControllerCreateSessionResponse> => {
  
  return customFetch<boardControllerCreateSessionResponse>(getBoardControllerCreateSessionUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createBoardSessionBodyDto,)
  }
);}


/**
 * @summary Danh sách phiên họp Hội đồng
 */
export type boardControllerGetSessionsResponse200 = {
  data: BoardSessionResDtoOutput[]
  status: 200
}
    
export type boardControllerGetSessionsResponseSuccess = (boardControllerGetSessionsResponse200) & {
  headers: Headers;
};
;

export type boardControllerGetSessionsResponse = (boardControllerGetSessionsResponseSuccess)

export const getBoardControllerGetSessionsUrl = () => {


  

  return `/board/sessions`
}

export const boardControllerGetSessions = async ( options?: RequestInit): Promise<boardControllerGetSessionsResponse> => {
  
  return customFetch<boardControllerGetSessionsResponse>(getBoardControllerGetSessionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Chi tiết phiên họp Hội đồng
 */
export type boardControllerGetSessionByIdResponse200 = {
  data: BoardSessionResDtoOutput
  status: 200
}
    
export type boardControllerGetSessionByIdResponseSuccess = (boardControllerGetSessionByIdResponse200) & {
  headers: Headers;
};
;

export type boardControllerGetSessionByIdResponse = (boardControllerGetSessionByIdResponseSuccess)

export const getBoardControllerGetSessionByIdUrl = ({ id }: BoardControllerGetSessionByIdPathParameters,) => {


  

  return `/board/sessions/${id}`
}

export const boardControllerGetSessionById = async ({ id }: BoardControllerGetSessionByIdPathParameters, options?: RequestInit): Promise<boardControllerGetSessionByIdResponse> => {
  
  return customFetch<boardControllerGetSessionByIdResponse>(getBoardControllerGetSessionByIdUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Kích hoạt phiên họp Hội đồng → ACTIVE
 */
export type boardControllerStartSessionResponse200 = {
  data: BoardSessionResDtoOutput
  status: 200
}
    
export type boardControllerStartSessionResponseSuccess = (boardControllerStartSessionResponse200) & {
  headers: Headers;
};
;

export type boardControllerStartSessionResponse = (boardControllerStartSessionResponseSuccess)

export const getBoardControllerStartSessionUrl = ({ id }: BoardControllerStartSessionPathParameters,) => {


  

  return `/board/sessions/${id}/start`
}

export const boardControllerStartSession = async ({ id }: BoardControllerStartSessionPathParameters, options?: RequestInit): Promise<boardControllerStartSessionResponse> => {
  
  return customFetch<boardControllerStartSessionResponse>(getBoardControllerStartSessionUrl({ id }),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}


/**
 * @summary Xem cấu hình biểu quyết Hội đồng hiện tại
 */
export type boardControllerGetConfigResponse200 = {
  data: BoardConfigResDtoOutput
  status: 200
}
    
export type boardControllerGetConfigResponseSuccess = (boardControllerGetConfigResponse200) & {
  headers: Headers;
};
;

export type boardControllerGetConfigResponse = (boardControllerGetConfigResponseSuccess)

export const getBoardControllerGetConfigUrl = () => {


  

  return `/board/config`
}

export const boardControllerGetConfig = async ( options?: RequestInit): Promise<boardControllerGetConfigResponse> => {
  
  return customFetch<boardControllerGetConfigResponse>(getBoardControllerGetConfigUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Editor tạo quyết định Hội đồng nháp → PENDING
 */
export type boardControllerCreateDecisionResponse201 = {
  data: BoardDecisionResDtoOutput
  status: 201
}
    
export type boardControllerCreateDecisionResponseSuccess = (boardControllerCreateDecisionResponse201) & {
  headers: Headers;
};
;

export type boardControllerCreateDecisionResponse = (boardControllerCreateDecisionResponseSuccess)

export const getBoardControllerCreateDecisionUrl = () => {


  

  return `/board/decisions`
}

export const boardControllerCreateDecision = async (createBoardDecisionBodyDto: CreateBoardDecisionBodyDto, options?: RequestInit): Promise<boardControllerCreateDecisionResponse> => {
  
  return customFetch<boardControllerCreateDecisionResponse>(getBoardControllerCreateDecisionUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createBoardDecisionBodyDto,)
  }
);}


/**
 * @summary Danh sách quyết định Hội đồng
 */
export type boardControllerGetDecisionsResponse200 = {
  data: BoardDecisionResDtoOutput[]
  status: 200
}
    
export type boardControllerGetDecisionsResponseSuccess = (boardControllerGetDecisionsResponse200) & {
  headers: Headers;
};
;

export type boardControllerGetDecisionsResponse = (boardControllerGetDecisionsResponseSuccess)

export const getBoardControllerGetDecisionsUrl = () => {


  

  return `/board/decisions`
}

export const boardControllerGetDecisions = async ( options?: RequestInit): Promise<boardControllerGetDecisionsResponse> => {
  
  return customFetch<boardControllerGetDecisionsResponse>(getBoardControllerGetDecisionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Chi tiết quyết định Hội đồng
 */
export type boardControllerGetDecisionDetailsResponse200 = {
  data: BoardDecisionResDtoOutput
  status: 200
}
    
export type boardControllerGetDecisionDetailsResponseSuccess = (boardControllerGetDecisionDetailsResponse200) & {
  headers: Headers;
};
;

export type boardControllerGetDecisionDetailsResponse = (boardControllerGetDecisionDetailsResponseSuccess)

export const getBoardControllerGetDecisionDetailsUrl = ({ id }: BoardControllerGetDecisionDetailsPathParameters,) => {


  

  return `/board/decisions/${id}`
}

export const boardControllerGetDecisionDetails = async ({ id }: BoardControllerGetDecisionDetailsPathParameters, options?: RequestInit): Promise<boardControllerGetDecisionDetailsResponse> => {
  
  return customFetch<boardControllerGetDecisionDetailsResponse>(getBoardControllerGetDecisionDetailsUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Danh sách phiếu biểu quyết của quyết định
 */
export type boardControllerGetDecisionVotesResponse200 = {
  data: BoardVoteResDtoOutput[]
  status: 200
}
    
export type boardControllerGetDecisionVotesResponseSuccess = (boardControllerGetDecisionVotesResponse200) & {
  headers: Headers;
};
;

export type boardControllerGetDecisionVotesResponse = (boardControllerGetDecisionVotesResponseSuccess)

export const getBoardControllerGetDecisionVotesUrl = ({ id }: BoardControllerGetDecisionVotesPathParameters,) => {


  

  return `/board/decisions/${id}/votes`
}

export const boardControllerGetDecisionVotes = async ({ id }: BoardControllerGetDecisionVotesPathParameters, options?: RequestInit): Promise<boardControllerGetDecisionVotesResponse> => {
  
  return customFetch<boardControllerGetDecisionVotesResponse>(getBoardControllerGetDecisionVotesUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Board/Editor bỏ phiếu cho quyết định → cập nhật kết quả
 */
export type boardControllerCastVoteResponse201 = {
  data: MessageResDtoOutput
  status: 201
}
    
export type boardControllerCastVoteResponseSuccess = (boardControllerCastVoteResponse201) & {
  headers: Headers;
};
;

export type boardControllerCastVoteResponse = (boardControllerCastVoteResponseSuccess)

export const getBoardControllerCastVoteUrl = ({ id }: BoardControllerCastVotePathParameters,) => {


  

  return `/board/decisions/${id}/vote`
}

export const boardControllerCastVote = async ({ id }: BoardControllerCastVotePathParameters,
    castVoteBodyDto: CastVoteBodyDto, options?: RequestInit): Promise<boardControllerCastVoteResponse> => {
  
  return customFetch<boardControllerCastVoteResponse>(getBoardControllerCastVoteUrl({ id }),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      castVoteBodyDto,)
  }
);}


/**
 * @summary Danh sách báo cáo Hội đồng
 */
export type boardControllerGetReportsResponse200 = {
  data: SeriesReportResDtoOutput[]
  status: 200
}
    
export type boardControllerGetReportsResponseSuccess = (boardControllerGetReportsResponse200) & {
  headers: Headers;
};
;

export type boardControllerGetReportsResponse = (boardControllerGetReportsResponseSuccess)

export const getBoardControllerGetReportsUrl = () => {


  

  return `/board/reports`
}

export const boardControllerGetReports = async ( options?: RequestInit): Promise<boardControllerGetReportsResponse> => {
  
  return customFetch<boardControllerGetReportsResponse>(getBoardControllerGetReportsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Editor tạo báo cáo phân tích series cho Hội đồng
 */
export type boardControllerCreateSeriesReportResponse201 = {
  data: SeriesReportResDtoOutput
  status: 201
}
    
export type boardControllerCreateSeriesReportResponseSuccess = (boardControllerCreateSeriesReportResponse201) & {
  headers: Headers;
};
;

export type boardControllerCreateSeriesReportResponse = (boardControllerCreateSeriesReportResponseSuccess)

export const getBoardControllerCreateSeriesReportUrl = () => {


  

  return `/board/reports`
}

export const boardControllerCreateSeriesReport = async (createSeriesReportBodyDto: CreateSeriesReportBodyDto, options?: RequestInit): Promise<boardControllerCreateSeriesReportResponse> => {
  
  return customFetch<boardControllerCreateSeriesReportResponse>(getBoardControllerCreateSeriesReportUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSeriesReportBodyDto,)
  }
);}


/**
 * @summary Chi tiết báo cáo Hội đồng
 */
export type boardControllerGetReportByIdResponse200 = {
  data: SeriesReportResDtoOutput
  status: 200
}
    
export type boardControllerGetReportByIdResponseSuccess = (boardControllerGetReportByIdResponse200) & {
  headers: Headers;
};
;

export type boardControllerGetReportByIdResponse = (boardControllerGetReportByIdResponseSuccess)

export const getBoardControllerGetReportByIdUrl = ({ id }: BoardControllerGetReportByIdPathParameters,) => {


  

  return `/board/reports/${id}`
}

export const boardControllerGetReportById = async ({ id }: BoardControllerGetReportByIdPathParameters, options?: RequestInit): Promise<boardControllerGetReportByIdResponse> => {
  
  return customFetch<boardControllerGetReportByIdResponse>(getBoardControllerGetReportByIdUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Super Admin cập nhật cấu hình biểu quyết Hội đồng
 */
export type boardControllerUpdateConfigResponse200 = {
  data: BoardConfigResDtoOutput
  status: 200
}
    
export type boardControllerUpdateConfigResponseSuccess = (boardControllerUpdateConfigResponse200) & {
  headers: Headers;
};
;

export type boardControllerUpdateConfigResponse = (boardControllerUpdateConfigResponseSuccess)

export const getBoardControllerUpdateConfigUrl = ({ id }: BoardControllerUpdateConfigPathParameters,) => {


  

  return `/board/config/${id}`
}

export const boardControllerUpdateConfig = async ({ id }: BoardControllerUpdateConfigPathParameters,
    updateBoardConfigBodyDto: UpdateBoardConfigBodyDto, options?: RequestInit): Promise<boardControllerUpdateConfigResponse> => {
  
  return customFetch<boardControllerUpdateConfigResponse>(getBoardControllerUpdateConfigUrl({ id }),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateBoardConfigBodyDto,)
  }
);}


