/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { ChapterProgressResDtoOutputNameStatus } from './chapterProgressResDtoOutputNameStatus';
import type { ChapterProgressResDtoOutputTaskBreakdown } from './chapterProgressResDtoOutputTaskBreakdown';
import type { ChapterProgressResDtoOutputWarningLevel } from './chapterProgressResDtoOutputWarningLevel';

export interface ChapterProgressResDtoOutput {
  chapterId: string;
  /**
   * null = chapter không gắn Name
   * @nullable
   */
  nameStatus: ChapterProgressResDtoOutputNameStatus;
  totalPages: number;
  /** Số trang đã hết task mở (sẵn sàng nộp) */
  pagesReady: number;
  /** Số trang còn task đang mở */
  pagesPending: number;
  taskBreakdown: ChapterProgressResDtoOutputTaskBreakdown;
  /** @nullable */
  deadline: string | null;
  /** @nullable */
  remainingHours: number | null;
  progressPct: number;
  /** Deadline warning: NONE an toan, YELLOW nguy co, RED kho kip, CRITICAL qua han. Values: NONE, YELLOW, RED, CRITICAL */
  warningLevel: ChapterProgressResDtoOutputWarningLevel;
  onHold: boolean;
}
