/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * The WDP API description
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AdminCreateUserResDtoOutput,
  AssistantProfileResDtoOutput,
  MangakaProfileResDtoOutput
} from '../../model/users';



export const getUsersControllerCreateUserMockHandler = (overrideResponse?: AdminCreateUserResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AdminCreateUserResDtoOutput> | AdminCreateUserResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/admin/users', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getUsersControllerUpsertMangakaProfileMockHandler = (overrideResponse?: MangakaProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<MangakaProfileResDtoOutput> | MangakaProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.put('*/me/mangaka-profile', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getUsersControllerGetMyMangakaProfileMockHandler = (overrideResponse?: MangakaProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MangakaProfileResDtoOutput> | MangakaProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/me/mangaka-profile', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getUsersControllerUpsertAssistantProfileMockHandler = (overrideResponse?: AssistantProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<AssistantProfileResDtoOutput> | AssistantProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.put('*/me/assistant-profile', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getUsersControllerGetMyAssistantProfileMockHandler = (overrideResponse?: AssistantProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AssistantProfileResDtoOutput> | AssistantProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/me/assistant-profile', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getUsersControllerGetMangakaProfileMockHandler = (overrideResponse?: MangakaProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MangakaProfileResDtoOutput> | MangakaProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/mangakas/:userId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getUsersControllerGetAssistantProfileMockHandler = (overrideResponse?: AssistantProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AssistantProfileResDtoOutput> | AssistantProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/assistants/:userId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getUsersMock = () => [
  getUsersControllerCreateUserMockHandler(),
  getUsersControllerUpsertMangakaProfileMockHandler(),
  getUsersControllerGetMyMangakaProfileMockHandler(),
  getUsersControllerUpsertAssistantProfileMockHandler(),
  getUsersControllerGetMyAssistantProfileMockHandler(),
  getUsersControllerGetMangakaProfileMockHandler(),
  getUsersControllerGetAssistantProfileMockHandler()
]
