/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AdminCreateUserResDtoOutput,
  AdminResetPasswordResDtoOutput,
  AdminStatsResDtoOutput,
  AdminUserListResDtoOutput,
  AdminUserResDtoOutput,
  AssistantDirectoryListResDtoOutput,
  AssistantProfileResDtoOutput,
  MangakaProfileResDtoOutput,
  MeResDtoOutput,
  MessageResDtoOutput,
  StaffProfileResDtoOutput
} from '../../model/users';


export const getUsersControllerCreateUserResponseMock = (overrideResponse: Partial< AdminCreateUserResDtoOutput > = {}): AdminCreateUserResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.string.alpha({length: {min: 10, max: 20}}), roleCode: faker.helpers.arrayElement(['MANGAKA','ASSISTANT','EDITOR','BOARD_MEMBER','SUPER_ADMIN'] as const), temporaryPassword: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getUsersControllerListUsersResponseMock = (overrideResponse: Partial< AdminUserListResDtoOutput > = {}): AdminUserListResDtoOutput => ({items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), phoneNumber: faker.string.alpha({length: {min: 10, max: 20}}), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), role: faker.helpers.arrayElement(['MANGAKA','ASSISTANT','EDITOR','BOARD_MEMBER','SUPER_ADMIN'] as const), status: faker.helpers.arrayElement(['INACTIVE','ACTIVE','BANNED','BLOCKED'] as const), emailVerified: faker.datatype.boolean(), registrationType: faker.helpers.arrayElement(['SELF_REGISTERED','ADMIN_CREATED'] as const), mustChangePassword: faker.datatype.boolean(), createdAt: faker.string.alpha({length: {min: 10, max: 20}})})), total: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), limit: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), offset: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ...overrideResponse})

export const getUsersControllerGetUserResponseMock = (overrideResponse: Partial< AdminUserResDtoOutput > = {}): AdminUserResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), phoneNumber: faker.string.alpha({length: {min: 10, max: 20}}), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), role: faker.helpers.arrayElement(['MANGAKA','ASSISTANT','EDITOR','BOARD_MEMBER','SUPER_ADMIN'] as const), status: faker.helpers.arrayElement(['INACTIVE','ACTIVE','BANNED','BLOCKED'] as const), emailVerified: faker.datatype.boolean(), registrationType: faker.helpers.arrayElement(['SELF_REGISTERED','ADMIN_CREATED'] as const), mustChangePassword: faker.datatype.boolean(), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getUsersControllerDeleteUserResponseMock = (overrideResponse: Partial< MessageResDtoOutput > = {}): MessageResDtoOutput => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getUsersControllerUpdateUserStatusResponseMock = (overrideResponse: Partial< AdminUserResDtoOutput > = {}): AdminUserResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), phoneNumber: faker.string.alpha({length: {min: 10, max: 20}}), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), role: faker.helpers.arrayElement(['MANGAKA','ASSISTANT','EDITOR','BOARD_MEMBER','SUPER_ADMIN'] as const), status: faker.helpers.arrayElement(['INACTIVE','ACTIVE','BANNED','BLOCKED'] as const), emailVerified: faker.datatype.boolean(), registrationType: faker.helpers.arrayElement(['SELF_REGISTERED','ADMIN_CREATED'] as const), mustChangePassword: faker.datatype.boolean(), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getUsersControllerRestoreUserResponseMock = (overrideResponse: Partial< AdminUserResDtoOutput > = {}): AdminUserResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), phoneNumber: faker.string.alpha({length: {min: 10, max: 20}}), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), role: faker.helpers.arrayElement(['MANGAKA','ASSISTANT','EDITOR','BOARD_MEMBER','SUPER_ADMIN'] as const), status: faker.helpers.arrayElement(['INACTIVE','ACTIVE','BANNED','BLOCKED'] as const), emailVerified: faker.datatype.boolean(), registrationType: faker.helpers.arrayElement(['SELF_REGISTERED','ADMIN_CREATED'] as const), mustChangePassword: faker.datatype.boolean(), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getUsersControllerResetUserPasswordResponseMock = (overrideResponse: Partial< AdminResetPasswordResDtoOutput > = {}): AdminResetPasswordResDtoOutput => ({temporaryPassword: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getUsersControllerGetAdminStatsResponseMock = (overrideResponse: Partial< AdminStatsResDtoOutput > = {}): AdminStatsResDtoOutput => ({users: {total: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), deleted: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), byStatus: {
        [faker.string.alphanumeric(5)]: faker.number.float({min: undefined, max: undefined, fractionDigits: 2})
      }, byRole: {
        [faker.string.alphanumeric(5)]: faker.number.float({min: undefined, max: undefined, fractionDigits: 2})
      }}, series: {total: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), byStatus: {
        [faker.string.alphanumeric(5)]: faker.number.float({min: undefined, max: undefined, fractionDigits: 2})
      }}, chapters: {total: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), published: faker.number.float({min: undefined, max: undefined, fractionDigits: 2})}, tasks: {total: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), byStatus: {
        [faker.string.alphanumeric(5)]: faker.number.float({min: undefined, max: undefined, fractionDigits: 2})
      }}, ...overrideResponse})

export const getUsersControllerGetMeResponseMock = (overrideResponse: Partial< MeResDtoOutput > = {}): MeResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), phoneNumber: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['MANGAKA','ASSISTANT','EDITOR','BOARD_MEMBER','SUPER_ADMIN'] as const), status: faker.helpers.arrayElement(['INACTIVE','ACTIVE','BANNED','BLOCKED'] as const), emailVerified: faker.datatype.boolean(), mustChangePassword: faker.datatype.boolean(), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getUsersControllerUpdateMeResponseMock = (overrideResponse: Partial< MeResDtoOutput > = {}): MeResDtoOutput => ({id: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), phoneNumber: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['MANGAKA','ASSISTANT','EDITOR','BOARD_MEMBER','SUPER_ADMIN'] as const), status: faker.helpers.arrayElement(['INACTIVE','ACTIVE','BANNED','BLOCKED'] as const), emailVerified: faker.datatype.boolean(), mustChangePassword: faker.datatype.boolean(), createdAt: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getUsersControllerUpsertMangakaProfileResponseMock = (overrideResponse: Partial< MangakaProfileResDtoOutput > = {}): MangakaProfileResDtoOutput => ({userId: faker.string.alpha({length: {min: 10, max: 20}}), penName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), genres: faker.helpers.arrayElements(['ACTION','ADVENTURE','COMEDY','DRAMA','FANTASY','HORROR','MYSTERY','ROMANCE','SCI_FI','SLICE_OF_LIFE','SPORTS','SUPERNATURAL','THRILLER','HISTORICAL','ISEKAI','MECHA','PSYCHOLOGICAL'] as const), experienceLevel: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), bio: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), portfolioFiles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), reputationScore: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingAvg: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), isRecommended: faker.datatype.boolean(), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), hasProfile: faker.datatype.boolean(), ...overrideResponse})

export const getUsersControllerGetMyMangakaProfileResponseMock = (overrideResponse: Partial< MangakaProfileResDtoOutput > = {}): MangakaProfileResDtoOutput => ({userId: faker.string.alpha({length: {min: 10, max: 20}}), penName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), genres: faker.helpers.arrayElements(['ACTION','ADVENTURE','COMEDY','DRAMA','FANTASY','HORROR','MYSTERY','ROMANCE','SCI_FI','SLICE_OF_LIFE','SPORTS','SUPERNATURAL','THRILLER','HISTORICAL','ISEKAI','MECHA','PSYCHOLOGICAL'] as const), experienceLevel: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), bio: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), portfolioFiles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), reputationScore: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingAvg: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), isRecommended: faker.datatype.boolean(), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), hasProfile: faker.datatype.boolean(), ...overrideResponse})

export const getUsersControllerUpsertAssistantProfileResponseMock = (overrideResponse: Partial< AssistantProfileResDtoOutput > = {}): AssistantProfileResDtoOutput => ({userId: faker.string.alpha({length: {min: 10, max: 20}}), specializations: faker.helpers.arrayElements(['BACKGROUND','SCREENTONE','EFFECT_LINES','INKING','COLORING','LETTERING'] as const), experienceLevel: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), portfolioFiles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), availabilityStatus: faker.helpers.arrayElement([faker.helpers.arrayElement(['AVAILABLE','BUSY','ON_LEAVE','UNAVAILABLE'] as const), null]), availabilityFrom: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), availabilityTo: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reputationScore: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingAvg: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), isRecommended: faker.datatype.boolean(), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), hasProfile: faker.datatype.boolean(), ...overrideResponse})

export const getUsersControllerGetMyAssistantProfileResponseMock = (overrideResponse: Partial< AssistantProfileResDtoOutput > = {}): AssistantProfileResDtoOutput => ({userId: faker.string.alpha({length: {min: 10, max: 20}}), specializations: faker.helpers.arrayElements(['BACKGROUND','SCREENTONE','EFFECT_LINES','INKING','COLORING','LETTERING'] as const), experienceLevel: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), portfolioFiles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), availabilityStatus: faker.helpers.arrayElement([faker.helpers.arrayElement(['AVAILABLE','BUSY','ON_LEAVE','UNAVAILABLE'] as const), null]), availabilityFrom: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), availabilityTo: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reputationScore: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingAvg: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), isRecommended: faker.datatype.boolean(), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), hasProfile: faker.datatype.boolean(), ...overrideResponse})

export const getUsersControllerGetMangakaProfileResponseMock = (overrideResponse: Partial< MangakaProfileResDtoOutput > = {}): MangakaProfileResDtoOutput => ({userId: faker.string.alpha({length: {min: 10, max: 20}}), penName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), genres: faker.helpers.arrayElements(['ACTION','ADVENTURE','COMEDY','DRAMA','FANTASY','HORROR','MYSTERY','ROMANCE','SCI_FI','SLICE_OF_LIFE','SPORTS','SUPERNATURAL','THRILLER','HISTORICAL','ISEKAI','MECHA','PSYCHOLOGICAL'] as const), experienceLevel: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), bio: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), portfolioFiles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), reputationScore: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingAvg: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), isRecommended: faker.datatype.boolean(), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), hasProfile: faker.datatype.boolean(), ...overrideResponse})

export const getUsersControllerListAssistantsResponseMock = (overrideResponse: Partial< AssistantDirectoryListResDtoOutput > = {}): AssistantDirectoryListResDtoOutput => ({items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({userId: faker.string.alpha({length: {min: 10, max: 20}}), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), specializations: faker.helpers.arrayElements(['BACKGROUND','SCREENTONE','EFFECT_LINES','INKING','COLORING','LETTERING'] as const), experienceLevel: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), portfolioFiles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), availabilityStatus: faker.helpers.arrayElement([faker.helpers.arrayElement(['AVAILABLE','BUSY','ON_LEAVE','UNAVAILABLE'] as const), null]), availabilityFrom: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), availabilityTo: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reputationScore: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingAvg: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), isRecommended: faker.datatype.boolean()})), total: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), limit: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), offset: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ...overrideResponse})

export const getUsersControllerGetAssistantProfileResponseMock = (overrideResponse: Partial< AssistantProfileResDtoOutput > = {}): AssistantProfileResDtoOutput => ({userId: faker.string.alpha({length: {min: 10, max: 20}}), specializations: faker.helpers.arrayElements(['BACKGROUND','SCREENTONE','EFFECT_LINES','INKING','COLORING','LETTERING'] as const), experienceLevel: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), portfolioFiles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), availabilityStatus: faker.helpers.arrayElement([faker.helpers.arrayElement(['AVAILABLE','BUSY','ON_LEAVE','UNAVAILABLE'] as const), null]), availabilityFrom: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), availabilityTo: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), reputationScore: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingAvg: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ratingCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), isRecommended: faker.datatype.boolean(), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), hasProfile: faker.datatype.boolean(), ...overrideResponse})

export const getUsersControllerUpsertStaffProfileResponseMock = (overrideResponse: Partial< StaffProfileResDtoOutput > = {}): StaffProfileResDtoOutput => ({userId: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['MANGAKA','ASSISTANT','EDITOR','BOARD_MEMBER','SUPER_ADMIN'] as const), specialtyGenres: faker.helpers.arrayElements(['ACTION','ADVENTURE','COMEDY','DRAMA','FANTASY','HORROR','MYSTERY','ROMANCE','SCI_FI','SLICE_OF_LIFE','SPORTS','SUPERNATURAL','THRILLER','HISTORICAL','ISEKAI','MECHA','PSYCHOLOGICAL'] as const), demographics: faker.helpers.arrayElements(['SHONEN','SEINEN','SHOJO','JOSEI','KODOMO'] as const), bio: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), yearsOfExperience: faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), null]), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), hasProfile: faker.datatype.boolean(), ...overrideResponse})

export const getUsersControllerGetMyStaffProfileResponseMock = (overrideResponse: Partial< StaffProfileResDtoOutput > = {}): StaffProfileResDtoOutput => ({userId: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['MANGAKA','ASSISTANT','EDITOR','BOARD_MEMBER','SUPER_ADMIN'] as const), specialtyGenres: faker.helpers.arrayElements(['ACTION','ADVENTURE','COMEDY','DRAMA','FANTASY','HORROR','MYSTERY','ROMANCE','SCI_FI','SLICE_OF_LIFE','SPORTS','SUPERNATURAL','THRILLER','HISTORICAL','ISEKAI','MECHA','PSYCHOLOGICAL'] as const), demographics: faker.helpers.arrayElements(['SHONEN','SEINEN','SHOJO','JOSEI','KODOMO'] as const), bio: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), yearsOfExperience: faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), null]), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), hasProfile: faker.datatype.boolean(), ...overrideResponse})

export const getUsersControllerGetStaffProfileResponseMock = (overrideResponse: Partial< StaffProfileResDtoOutput > = {}): StaffProfileResDtoOutput => ({userId: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['MANGAKA','ASSISTANT','EDITOR','BOARD_MEMBER','SUPER_ADMIN'] as const), specialtyGenres: faker.helpers.arrayElements(['ACTION','ADVENTURE','COMEDY','DRAMA','FANTASY','HORROR','MYSTERY','ROMANCE','SCI_FI','SLICE_OF_LIFE','SPORTS','SUPERNATURAL','THRILLER','HISTORICAL','ISEKAI','MECHA','PSYCHOLOGICAL'] as const), demographics: faker.helpers.arrayElements(['SHONEN','SEINEN','SHOJO','JOSEI','KODOMO'] as const), bio: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), yearsOfExperience: faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), null]), displayName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), avatar: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), hasProfile: faker.datatype.boolean(), ...overrideResponse})


export const getUsersControllerCreateUserMockHandler = (overrideResponse?: AdminCreateUserResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AdminCreateUserResDtoOutput> | AdminCreateUserResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/admin/users', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerCreateUserResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerListUsersMockHandler = (overrideResponse?: AdminUserListResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AdminUserListResDtoOutput> | AdminUserListResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/admin/users', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerListUsersResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerGetUserMockHandler = (overrideResponse?: AdminUserResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AdminUserResDtoOutput> | AdminUserResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/admin/users/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerGetUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerDeleteUserMockHandler = (overrideResponse?: MessageResDtoOutput | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<MessageResDtoOutput> | MessageResDtoOutput), options?: RequestHandlerOptions) => {
  return http.delete('*/admin/users/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerDeleteUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerUpdateUserStatusMockHandler = (overrideResponse?: AdminUserResDtoOutput | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<AdminUserResDtoOutput> | AdminUserResDtoOutput), options?: RequestHandlerOptions) => {
  return http.patch('*/admin/users/:id/status', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerUpdateUserStatusResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerRestoreUserMockHandler = (overrideResponse?: AdminUserResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AdminUserResDtoOutput> | AdminUserResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/admin/users/:id/restore', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerRestoreUserResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerResetUserPasswordMockHandler = (overrideResponse?: AdminResetPasswordResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AdminResetPasswordResDtoOutput> | AdminResetPasswordResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/admin/users/:id/reset-password', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerResetUserPasswordResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerGetAdminStatsMockHandler = (overrideResponse?: AdminStatsResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AdminStatsResDtoOutput> | AdminStatsResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/admin/stats', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerGetAdminStatsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerGetMeMockHandler = (overrideResponse?: MeResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MeResDtoOutput> | MeResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/me', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerGetMeResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerUpdateMeMockHandler = (overrideResponse?: MeResDtoOutput | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<MeResDtoOutput> | MeResDtoOutput), options?: RequestHandlerOptions) => {
  return http.patch('*/me', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerUpdateMeResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerUpsertMangakaProfileMockHandler = (overrideResponse?: MangakaProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<MangakaProfileResDtoOutput> | MangakaProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.put('*/me/mangaka-profile', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerUpsertMangakaProfileResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerGetMyMangakaProfileMockHandler = (overrideResponse?: MangakaProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MangakaProfileResDtoOutput> | MangakaProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/me/mangaka-profile', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerGetMyMangakaProfileResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerUpsertAssistantProfileMockHandler = (overrideResponse?: AssistantProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<AssistantProfileResDtoOutput> | AssistantProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.put('*/me/assistant-profile', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerUpsertAssistantProfileResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerGetMyAssistantProfileMockHandler = (overrideResponse?: AssistantProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AssistantProfileResDtoOutput> | AssistantProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/me/assistant-profile', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerGetMyAssistantProfileResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerGetMangakaProfileMockHandler = (overrideResponse?: MangakaProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MangakaProfileResDtoOutput> | MangakaProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/mangakas/:userId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerGetMangakaProfileResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerListAssistantsMockHandler = (overrideResponse?: AssistantDirectoryListResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AssistantDirectoryListResDtoOutput> | AssistantDirectoryListResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/assistants', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerListAssistantsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerGetAssistantProfileMockHandler = (overrideResponse?: AssistantProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AssistantProfileResDtoOutput> | AssistantProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/assistants/:userId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerGetAssistantProfileResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerUpsertStaffProfileMockHandler = (overrideResponse?: StaffProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<StaffProfileResDtoOutput> | StaffProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.put('*/me/staff-profile', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerUpsertStaffProfileResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerGetMyStaffProfileMockHandler = (overrideResponse?: StaffProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StaffProfileResDtoOutput> | StaffProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/me/staff-profile', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerGetMyStaffProfileResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUsersControllerGetStaffProfileMockHandler = (overrideResponse?: StaffProfileResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StaffProfileResDtoOutput> | StaffProfileResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/staff/:userId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUsersControllerGetStaffProfileResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getUsersMock = () => [
  getUsersControllerCreateUserMockHandler(),
  getUsersControllerListUsersMockHandler(),
  getUsersControllerGetUserMockHandler(),
  getUsersControllerDeleteUserMockHandler(),
  getUsersControllerUpdateUserStatusMockHandler(),
  getUsersControllerRestoreUserMockHandler(),
  getUsersControllerResetUserPasswordMockHandler(),
  getUsersControllerGetAdminStatsMockHandler(),
  getUsersControllerGetMeMockHandler(),
  getUsersControllerUpdateMeMockHandler(),
  getUsersControllerUpsertMangakaProfileMockHandler(),
  getUsersControllerGetMyMangakaProfileMockHandler(),
  getUsersControllerUpsertAssistantProfileMockHandler(),
  getUsersControllerGetMyAssistantProfileMockHandler(),
  getUsersControllerGetMangakaProfileMockHandler(),
  getUsersControllerListAssistantsMockHandler(),
  getUsersControllerGetAssistantProfileMockHandler(),
  getUsersControllerUpsertStaffProfileMockHandler(),
  getUsersControllerGetMyStaffProfileMockHandler(),
  getUsersControllerGetStaffProfileMockHandler()
]
