/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type {
  AdminCreateUserBodyDto,
  AdminCreateUserResDtoOutput,
  AdminResetPasswordResDtoOutput,
  AdminStatsResDtoOutput,
  AdminUpdateUserStatusBodyDto,
  AdminUserListResDtoOutput,
  AdminUserResDtoOutput,
  AssistantDirectoryListResDtoOutput,
  AssistantProfileBodyDto,
  AssistantProfileResDtoOutput,
  MangakaDirectoryListResDtoOutput,
  MangakaProfileBodyDto,
  MangakaProfileResDtoOutput,
  MeResDtoOutput,
  MessageResDtoOutput,
  StaffProfileBodyDto,
  StaffProfileResDtoOutput,
  UpdateMeBodyDto,
  UsersControllerDeleteUserPathParameters,
  UsersControllerGetAssistantProfilePathParameters,
  UsersControllerGetMangakaProfilePathParameters,
  UsersControllerGetStaffProfilePathParameters,
  UsersControllerGetUserPathParameters,
  UsersControllerListAssistantsParams,
  UsersControllerListMangakasParams,
  UsersControllerListUsersParams,
  UsersControllerResetUserPasswordPathParameters,
  UsersControllerRestoreUserPathParameters,
  UsersControllerUpdateUserStatusPathParameters
} from '../../model/users';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Super Admin tạo Editor/Board → status=ACTIVE, registrationType=ADMIN_CREATED, mật khẩu tạm
 */
export type usersControllerCreateUserResponse201 = {
  data: AdminCreateUserResDtoOutput
  status: 201
}

export type usersControllerCreateUserResponse422 = {
  data: void
  status: 422
}
    
export type usersControllerCreateUserResponseSuccess = (usersControllerCreateUserResponse201) & {
  headers: Headers;
};
export type usersControllerCreateUserResponseError = (usersControllerCreateUserResponse422) & {
  headers: Headers;
};

export type usersControllerCreateUserResponse = (usersControllerCreateUserResponseSuccess | usersControllerCreateUserResponseError)

export const getUsersControllerCreateUserUrl = () => {


  

  return `/admin/users`
}

export const usersControllerCreateUser = async (adminCreateUserBodyDto: AdminCreateUserBodyDto, options?: RequestInit): Promise<usersControllerCreateUserResponse> => {
  
  return customFetch<usersControllerCreateUserResponse>(getUsersControllerCreateUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminCreateUserBodyDto,)
  }
);}


/**
 * @summary Super Admin liệt kê user (filter roleCode/status/search, phân trang, ẩn chính mình + soft-deleted)
 */
export type usersControllerListUsersResponse200 = {
  data: AdminUserListResDtoOutput
  status: 200
}
    
export type usersControllerListUsersResponseSuccess = (usersControllerListUsersResponse200) & {
  headers: Headers;
};
;

export type usersControllerListUsersResponse = (usersControllerListUsersResponseSuccess)

export const getUsersControllerListUsersUrl = (params?: UsersControllerListUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/users?${stringifiedParams}` : `/admin/users`
}

export const usersControllerListUsers = async (params?: UsersControllerListUsersParams, options?: RequestInit): Promise<usersControllerListUsersResponse> => {
  
  return customFetch<usersControllerListUsersResponse>(getUsersControllerListUsersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Super Admin xem chi tiết 1 user
 */
export type usersControllerGetUserResponse200 = {
  data: AdminUserResDtoOutput
  status: 200
}
    
export type usersControllerGetUserResponseSuccess = (usersControllerGetUserResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetUserResponse = (usersControllerGetUserResponseSuccess)

export const getUsersControllerGetUserUrl = ({ id }: UsersControllerGetUserPathParameters,) => {


  

  return `/admin/users/${id}`
}

export const usersControllerGetUser = async ({ id }: UsersControllerGetUserPathParameters, options?: RequestInit): Promise<usersControllerGetUserResponse> => {
  
  return customFetch<usersControllerGetUserResponse>(getUsersControllerGetUserUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Super Admin xóa mềm user (set deletedAt) + thu hồi toàn bộ refresh token
 */
export type usersControllerDeleteUserResponse200 = {
  data: MessageResDtoOutput
  status: 200
}
    
export type usersControllerDeleteUserResponseSuccess = (usersControllerDeleteUserResponse200) & {
  headers: Headers;
};
;

export type usersControllerDeleteUserResponse = (usersControllerDeleteUserResponseSuccess)

export const getUsersControllerDeleteUserUrl = ({ id }: UsersControllerDeleteUserPathParameters,) => {


  

  return `/admin/users/${id}`
}

export const usersControllerDeleteUser = async ({ id }: UsersControllerDeleteUserPathParameters, options?: RequestInit): Promise<usersControllerDeleteUserResponse> => {
  
  return customFetch<usersControllerDeleteUserResponse>(getUsersControllerDeleteUserUrl({ id }),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * @summary Super Admin ban/block/unban user (ACTIVE/BANNED/BLOCKED) — phạt thì revoke refresh + notify
 */
export type usersControllerUpdateUserStatusResponse200 = {
  data: AdminUserResDtoOutput
  status: 200
}
    
export type usersControllerUpdateUserStatusResponseSuccess = (usersControllerUpdateUserStatusResponse200) & {
  headers: Headers;
};
;

export type usersControllerUpdateUserStatusResponse = (usersControllerUpdateUserStatusResponseSuccess)

export const getUsersControllerUpdateUserStatusUrl = ({ id }: UsersControllerUpdateUserStatusPathParameters,) => {


  

  return `/admin/users/${id}/status`
}

export const usersControllerUpdateUserStatus = async ({ id }: UsersControllerUpdateUserStatusPathParameters,
    adminUpdateUserStatusBodyDto: AdminUpdateUserStatusBodyDto, options?: RequestInit): Promise<usersControllerUpdateUserStatusResponse> => {
  
  return customFetch<usersControllerUpdateUserStatusResponse>(getUsersControllerUpdateUserStatusUrl({ id }),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminUpdateUserStatusBodyDto,)
  }
);}


/**
 * @summary Super Admin khôi phục user đã xóa mềm (unset deletedAt — về absent)
 */
export type usersControllerRestoreUserResponse201 = {
  data: AdminUserResDtoOutput
  status: 201
}
    
export type usersControllerRestoreUserResponseSuccess = (usersControllerRestoreUserResponse201) & {
  headers: Headers;
};
;

export type usersControllerRestoreUserResponse = (usersControllerRestoreUserResponseSuccess)

export const getUsersControllerRestoreUserUrl = ({ id }: UsersControllerRestoreUserPathParameters,) => {


  

  return `/admin/users/${id}/restore`
}

export const usersControllerRestoreUser = async ({ id }: UsersControllerRestoreUserPathParameters, options?: RequestInit): Promise<usersControllerRestoreUserResponse> => {
  
  return customFetch<usersControllerRestoreUserResponse>(getUsersControllerRestoreUserUrl({ id }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Super Admin cấp mật khẩu tạm (trả 1 lần) + mustChangePassword + revoke refresh + email best-effort
 */
export type usersControllerResetUserPasswordResponse201 = {
  data: AdminResetPasswordResDtoOutput
  status: 201
}
    
export type usersControllerResetUserPasswordResponseSuccess = (usersControllerResetUserPasswordResponse201) & {
  headers: Headers;
};
;

export type usersControllerResetUserPasswordResponse = (usersControllerResetUserPasswordResponseSuccess)

export const getUsersControllerResetUserPasswordUrl = ({ id }: UsersControllerResetUserPasswordPathParameters,) => {


  

  return `/admin/users/${id}/reset-password`
}

export const usersControllerResetUserPassword = async ({ id }: UsersControllerResetUserPasswordPathParameters, options?: RequestInit): Promise<usersControllerResetUserPasswordResponse> => {
  
  return customFetch<usersControllerResetUserPasswordResponse>(getUsersControllerResetUserPasswordUrl({ id }),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Super Admin: số liệu tổng quan users/series/chapters/tasks (groupBy snapshot)
 */
export type usersControllerGetAdminStatsResponse200 = {
  data: AdminStatsResDtoOutput
  status: 200
}
    
export type usersControllerGetAdminStatsResponseSuccess = (usersControllerGetAdminStatsResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetAdminStatsResponse = (usersControllerGetAdminStatsResponseSuccess)

export const getUsersControllerGetAdminStatsUrl = () => {


  

  return `/admin/stats`
}

export const usersControllerGetAdminStats = async ( options?: RequestInit): Promise<usersControllerGetAdminStatsResponse> => {
  
  return customFetch<usersControllerGetAdminStatsResponse>(getUsersControllerGetAdminStatsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Xem thông tin tài khoản của chính mình (mọi role)
 */
export type usersControllerGetMeResponse200 = {
  data: MeResDtoOutput
  status: 200
}
    
export type usersControllerGetMeResponseSuccess = (usersControllerGetMeResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetMeResponse = (usersControllerGetMeResponseSuccess)

export const getUsersControllerGetMeUrl = () => {


  

  return `/me`
}

export const usersControllerGetMe = async ( options?: RequestInit): Promise<usersControllerGetMeResponse> => {
  
  return customFetch<usersControllerGetMeResponse>(getUsersControllerGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Cập nhật thông tin tài khoản của chính mình (name/displayName/avatar/phoneNumber). '' = xoá field nullable
 */
export type usersControllerUpdateMeResponse200 = {
  data: MeResDtoOutput
  status: 200
}

export type usersControllerUpdateMeResponse422 = {
  data: void
  status: 422
}
    
export type usersControllerUpdateMeResponseSuccess = (usersControllerUpdateMeResponse200) & {
  headers: Headers;
};
export type usersControllerUpdateMeResponseError = (usersControllerUpdateMeResponse422) & {
  headers: Headers;
};

export type usersControllerUpdateMeResponse = (usersControllerUpdateMeResponseSuccess | usersControllerUpdateMeResponseError)

export const getUsersControllerUpdateMeUrl = () => {


  

  return `/me`
}

export const usersControllerUpdateMe = async (updateMeBodyDto: UpdateMeBodyDto, options?: RequestInit): Promise<usersControllerUpdateMeResponse> => {
  
  return customFetch<usersControllerUpdateMeResponse>(getUsersControllerUpdateMeUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateMeBodyDto,)
  }
);}


/**
 * @summary Mangaka tạo/cập nhật hồ sơ của mình (penName/genres/level/bio/portfolio) — lazy 1:1
 */
export type usersControllerUpsertMangakaProfileResponse200 = {
  data: MangakaProfileResDtoOutput
  status: 200
}

export type usersControllerUpsertMangakaProfileResponse422 = {
  data: void
  status: 422
}
    
export type usersControllerUpsertMangakaProfileResponseSuccess = (usersControllerUpsertMangakaProfileResponse200) & {
  headers: Headers;
};
export type usersControllerUpsertMangakaProfileResponseError = (usersControllerUpsertMangakaProfileResponse422) & {
  headers: Headers;
};

export type usersControllerUpsertMangakaProfileResponse = (usersControllerUpsertMangakaProfileResponseSuccess | usersControllerUpsertMangakaProfileResponseError)

export const getUsersControllerUpsertMangakaProfileUrl = () => {


  

  return `/me/mangaka-profile`
}

export const usersControllerUpsertMangakaProfile = async (mangakaProfileBodyDto: MangakaProfileBodyDto, options?: RequestInit): Promise<usersControllerUpsertMangakaProfileResponse> => {
  
  return customFetch<usersControllerUpsertMangakaProfileResponse>(getUsersControllerUpsertMangakaProfileUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      mangakaProfileBodyDto,)
  }
);}


/**
 * @summary Mangaka xem hồ sơ của mình
 */
export type usersControllerGetMyMangakaProfileResponse200 = {
  data: MangakaProfileResDtoOutput
  status: 200
}
    
export type usersControllerGetMyMangakaProfileResponseSuccess = (usersControllerGetMyMangakaProfileResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetMyMangakaProfileResponse = (usersControllerGetMyMangakaProfileResponseSuccess)

export const getUsersControllerGetMyMangakaProfileUrl = () => {


  

  return `/me/mangaka-profile`
}

export const usersControllerGetMyMangakaProfile = async ( options?: RequestInit): Promise<usersControllerGetMyMangakaProfileResponse> => {
  
  return customFetch<usersControllerGetMyMangakaProfileResponse>(getUsersControllerGetMyMangakaProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Assistant tạo/cập nhật hồ sơ của mình (specializations/level/availability) — lazy 1:1
 */
export type usersControllerUpsertAssistantProfileResponse200 = {
  data: AssistantProfileResDtoOutput
  status: 200
}

export type usersControllerUpsertAssistantProfileResponse422 = {
  data: void
  status: 422
}
    
export type usersControllerUpsertAssistantProfileResponseSuccess = (usersControllerUpsertAssistantProfileResponse200) & {
  headers: Headers;
};
export type usersControllerUpsertAssistantProfileResponseError = (usersControllerUpsertAssistantProfileResponse422) & {
  headers: Headers;
};

export type usersControllerUpsertAssistantProfileResponse = (usersControllerUpsertAssistantProfileResponseSuccess | usersControllerUpsertAssistantProfileResponseError)

export const getUsersControllerUpsertAssistantProfileUrl = () => {


  

  return `/me/assistant-profile`
}

export const usersControllerUpsertAssistantProfile = async (assistantProfileBodyDto: AssistantProfileBodyDto, options?: RequestInit): Promise<usersControllerUpsertAssistantProfileResponse> => {
  
  return customFetch<usersControllerUpsertAssistantProfileResponse>(getUsersControllerUpsertAssistantProfileUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assistantProfileBodyDto,)
  }
);}


/**
 * @summary Assistant xem hồ sơ của mình
 */
export type usersControllerGetMyAssistantProfileResponse200 = {
  data: AssistantProfileResDtoOutput
  status: 200
}
    
export type usersControllerGetMyAssistantProfileResponseSuccess = (usersControllerGetMyAssistantProfileResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetMyAssistantProfileResponse = (usersControllerGetMyAssistantProfileResponseSuccess)

export const getUsersControllerGetMyAssistantProfileUrl = () => {


  

  return `/me/assistant-profile`
}

export const usersControllerGetMyAssistantProfile = async ( options?: RequestInit): Promise<usersControllerGetMyAssistantProfileResponse> => {
  
  return customFetch<usersControllerGetMyAssistantProfileResponse>(getUsersControllerGetMyAssistantProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Danh bạ Mangaka: tìm theo tên/penName, lọc genre/level; ưu tiên isRecommended/reputation (ẩn email/phone)
 */
export type usersControllerListMangakasResponse200 = {
  data: MangakaDirectoryListResDtoOutput
  status: 200
}
    
export type usersControllerListMangakasResponseSuccess = (usersControllerListMangakasResponse200) & {
  headers: Headers;
};
;

export type usersControllerListMangakasResponse = (usersControllerListMangakasResponseSuccess)

export const getUsersControllerListMangakasUrl = (params?: UsersControllerListMangakasParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/mangakas?${stringifiedParams}` : `/mangakas`
}

export const usersControllerListMangakas = async (params?: UsersControllerListMangakasParams, options?: RequestInit): Promise<usersControllerListMangakasResponse> => {
  
  return customFetch<usersControllerListMangakasResponse>(getUsersControllerListMangakasUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Xem hồ sơ Mangaka công khai (kèm reputation)
 */
export type usersControllerGetMangakaProfileResponse200 = {
  data: MangakaProfileResDtoOutput
  status: 200
}
    
export type usersControllerGetMangakaProfileResponseSuccess = (usersControllerGetMangakaProfileResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetMangakaProfileResponse = (usersControllerGetMangakaProfileResponseSuccess)

export const getUsersControllerGetMangakaProfileUrl = ({ userId }: UsersControllerGetMangakaProfilePathParameters,) => {


  

  return `/mangakas/${userId}`
}

export const usersControllerGetMangakaProfile = async ({ userId }: UsersControllerGetMangakaProfilePathParameters, options?: RequestInit): Promise<usersControllerGetMangakaProfileResponse> => {
  
  return customFetch<usersControllerGetMangakaProfileResponse>(getUsersControllerGetMangakaProfileUrl({ userId }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Danh bạ trợ lý: tìm theo tên, lọc specialization/level/availability, ưu tiên isRecommended/reputation (ẩn email/phone)
 */
export type usersControllerListAssistantsResponse200 = {
  data: AssistantDirectoryListResDtoOutput
  status: 200
}
    
export type usersControllerListAssistantsResponseSuccess = (usersControllerListAssistantsResponse200) & {
  headers: Headers;
};
;

export type usersControllerListAssistantsResponse = (usersControllerListAssistantsResponseSuccess)

export const getUsersControllerListAssistantsUrl = (params?: UsersControllerListAssistantsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/assistants?${stringifiedParams}` : `/assistants`
}

export const usersControllerListAssistants = async (params?: UsersControllerListAssistantsParams, options?: RequestInit): Promise<usersControllerListAssistantsResponse> => {
  
  return customFetch<usersControllerListAssistantsResponse>(getUsersControllerListAssistantsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Xem hồ sơ Assistant công khai (danh bạ; kèm reputation/availability)
 */
export type usersControllerGetAssistantProfileResponse200 = {
  data: AssistantProfileResDtoOutput
  status: 200
}
    
export type usersControllerGetAssistantProfileResponseSuccess = (usersControllerGetAssistantProfileResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetAssistantProfileResponse = (usersControllerGetAssistantProfileResponseSuccess)

export const getUsersControllerGetAssistantProfileUrl = ({ userId }: UsersControllerGetAssistantProfilePathParameters,) => {


  

  return `/assistants/${userId}`
}

export const usersControllerGetAssistantProfile = async ({ userId }: UsersControllerGetAssistantProfilePathParameters, options?: RequestInit): Promise<usersControllerGetAssistantProfileResponse> => {
  
  return customFetch<usersControllerGetAssistantProfileResponse>(getUsersControllerGetAssistantProfileUrl({ userId }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Editor/Board tạo/cập nhật hồ sơ của mình (specialtyGenres/demographics/bio) — lazy 1:1
 */
export type usersControllerUpsertStaffProfileResponse200 = {
  data: StaffProfileResDtoOutput
  status: 200
}

export type usersControllerUpsertStaffProfileResponse422 = {
  data: void
  status: 422
}
    
export type usersControllerUpsertStaffProfileResponseSuccess = (usersControllerUpsertStaffProfileResponse200) & {
  headers: Headers;
};
export type usersControllerUpsertStaffProfileResponseError = (usersControllerUpsertStaffProfileResponse422) & {
  headers: Headers;
};

export type usersControllerUpsertStaffProfileResponse = (usersControllerUpsertStaffProfileResponseSuccess | usersControllerUpsertStaffProfileResponseError)

export const getUsersControllerUpsertStaffProfileUrl = () => {


  

  return `/me/staff-profile`
}

export const usersControllerUpsertStaffProfile = async (staffProfileBodyDto: StaffProfileBodyDto, options?: RequestInit): Promise<usersControllerUpsertStaffProfileResponse> => {
  
  return customFetch<usersControllerUpsertStaffProfileResponse>(getUsersControllerUpsertStaffProfileUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      staffProfileBodyDto,)
  }
);}


/**
 * @summary Editor/Board xem hồ sơ của mình
 */
export type usersControllerGetMyStaffProfileResponse200 = {
  data: StaffProfileResDtoOutput
  status: 200
}
    
export type usersControllerGetMyStaffProfileResponseSuccess = (usersControllerGetMyStaffProfileResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetMyStaffProfileResponse = (usersControllerGetMyStaffProfileResponseSuccess)

export const getUsersControllerGetMyStaffProfileUrl = () => {


  

  return `/me/staff-profile`
}

export const usersControllerGetMyStaffProfile = async ( options?: RequestInit): Promise<usersControllerGetMyStaffProfileResponse> => {
  
  return customFetch<usersControllerGetMyStaffProfileResponse>(getUsersControllerGetMyStaffProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Xem hồ sơ Editor/Board công khai (ẩn email/phone)
 */
export type usersControllerGetStaffProfileResponse200 = {
  data: StaffProfileResDtoOutput
  status: 200
}
    
export type usersControllerGetStaffProfileResponseSuccess = (usersControllerGetStaffProfileResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetStaffProfileResponse = (usersControllerGetStaffProfileResponseSuccess)

export const getUsersControllerGetStaffProfileUrl = ({ userId }: UsersControllerGetStaffProfilePathParameters,) => {


  

  return `/staff/${userId}`
}

export const usersControllerGetStaffProfile = async ({ userId }: UsersControllerGetStaffProfilePathParameters, options?: RequestInit): Promise<usersControllerGetStaffProfileResponse> => {
  
  return customFetch<usersControllerGetStaffProfileResponse>(getUsersControllerGetStaffProfileUrl({ userId }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


