import { SITE } from './site'

type TitleRoute = readonly [pattern: RegExp, title: string]

const TITLE_ROUTES: readonly TitleRoute[] = [
  [/^\/$/, 'Trang chủ'],
  [/^\/login$/, 'Đăng nhập'],
  [/^\/register$/, 'Đăng ký tài khoản'],
  [/^\/change-password$/, 'Đổi mật khẩu'],

  [/^\/dashboard\/mangaka$/, 'Bảng điều khiển Mangaka'],
  [/^\/dashboard\/mangaka\/series\/propose$/, 'Đề xuất bộ truyện mới'],
  [/^\/dashboard\/mangaka\/series\/[^/]+\/edit$/, 'Chỉnh sửa hồ sơ bộ truyện'],
  [/^\/dashboard\/mangaka\/series\/[^/]+$/, 'Chi tiết bộ truyện'],
  [/^\/dashboard\/mangaka\/series$/, 'Bộ truyện của tôi'],
  [/^\/dashboard\/mangaka\/contracts\/[^/]+$/, 'Chi tiết hợp đồng'],
  [/^\/dashboard\/mangaka\/contracts$/, 'Hợp đồng'],
  [/^\/dashboard\/mangaka\/reprints$/, 'Yêu cầu tái bản'],
  [/^\/dashboard\/mangaka\/transfers$/, 'Chuyển nhượng bộ truyện'],
  [/^\/dashboard\/mangaka\/studio$/, 'Studio của tôi'],
  [/^\/dashboard\/mangaka\/assistants$/, 'Danh bạ trợ lý'],
  [/^\/dashboard\/mangaka\/profile$/, 'Hồ sơ Mangaka'],

  [/^\/dashboard\/assistant$/, 'Bảng điều khiển Trợ lý'],
  [/^\/dashboard\/assistant\/tasks$/, 'Công việc của tôi'],
  [/^\/dashboard\/assistant\/studio$/, 'Studio cộng tác'],
  [/^\/dashboard\/assistant\/invites$/, 'Lời mời cộng tác'],
  [/^\/dashboard\/assistant\/notifications$/, 'Thông báo'],
  [/^\/dashboard\/assistant\/profile$/, 'Hồ sơ Trợ lý'],

  [/^\/dashboard\/editor$/, 'Bảng điều khiển Editor'],
  [/^\/dashboard\/editor\/proposals\/[^/]+$/, 'Duyệt hồ sơ bộ truyện'],
  [/^\/dashboard\/editor\/proposals$/, 'Hàng đợi hồ sơ'],
  [/^\/dashboard\/editor\/board\/pitching$/, 'Trình bộ truyện lên Hội đồng'],
  [/^\/dashboard\/editor\/board\/sessions\/[^/]+$/, 'Chi tiết phiên Hội đồng'],
  [/^\/dashboard\/editor\/board\/sessions$/, 'Phiên Hội đồng'],
  [/^\/dashboard\/editor\/board\/decisions\/[^/]+$/, 'Chi tiết quyết định Hội đồng'],
  [/^\/dashboard\/editor\/board\/decisions$/, 'Quyết định Hội đồng'],
  [/^\/dashboard\/editor\/board\/reports$/, 'Báo cáo Hội đồng'],
  [/^\/dashboard\/editor\/board\/lifecycle$/, 'Quyết định vòng đời bộ truyện'],
  [/^\/dashboard\/editor\/board$/, 'Quy trình Hội đồng'],
  [/^\/dashboard\/editor\/contracts\/[^/]+\/terms$/, 'Điều khoản hợp đồng'],
  [/^\/dashboard\/editor\/contracts\/[^/]+\/conditions$/, 'Điều kiện thanh toán'],
  [/^\/dashboard\/editor\/contracts\/[^/]+\/history$/, 'Lịch sử hợp đồng'],
  [/^\/dashboard\/editor\/contracts\/[^/]+\/revenue$/, 'Doanh thu hợp đồng'],
  [/^\/dashboard\/editor\/contracts\/[^/]+\/amendments$/, 'Phụ lục hợp đồng'],
  [/^\/dashboard\/editor\/contracts\/[^/]+$/, 'Chi tiết hợp đồng'],
  [/^\/dashboard\/editor\/contracts$/, 'Quản lý hợp đồng'],
  [/^\/dashboard\/editor\/operations\/lifecycle$/, 'Vòng đời bộ truyện'],
  [/^\/dashboard\/editor\/operations\/sales$/, 'Doanh số xuất bản'],
  [/^\/dashboard\/editor\/operations\/reviews$/, 'Đánh giá Mangaka'],
  [/^\/dashboard\/editor\/operations\/deadlines$/, 'Quản lý thời hạn'],
  [/^\/dashboard\/editor\/operations\/surveys$/, 'Khảo sát và xếp hạng'],
  [/^\/dashboard\/editor\/operations\/reprints$/, 'Quy trình tái bản'],
  [/^\/dashboard\/editor\/operations\/transfers$/, 'Quy trình chuyển nhượng'],
  [/^\/dashboard\/editor\/operations\/versions$/, 'Phiên bản phát hành'],
  [/^\/dashboard\/editor\/operations$/, 'Vận hành biên tập'],
  [/^\/dashboard\/editor\/notifications$/, 'Thông báo Editor'],
  [/^\/dashboard\/editor\/profile$/, 'Hồ sơ Editor'],
  [/^\/dashboard\/editor\/publication\/[^/]+\/[^/]+$/, 'Duyệt chương xuất bản'],
  [/^\/dashboard\/editor\/publication$/, 'Kiểm duyệt xuất bản'],

  [/^\/dashboard\/board$/, 'Bảng điều khiển Hội đồng'],
  [/^\/dashboard\/board\/sessions\/[^/]+$/, 'Chi tiết phiên Hội đồng'],
  [/^\/dashboard\/board\/sessions$/, 'Phiên Hội đồng'],
  [/^\/dashboard\/board\/decisions\/[^/]+$/, 'Chi tiết quyết định Hội đồng'],
  [/^\/dashboard\/board\/decisions$/, 'Quyết định Hội đồng'],
  [/^\/dashboard\/board\/reports$/, 'Báo cáo Hội đồng'],
  [/^\/dashboard\/board\/contracts\/[^/]+$/, 'Chi tiết hợp đồng'],
  [/^\/dashboard\/board\/contracts$/, 'Duyệt hợp đồng'],
  [/^\/dashboard\/board\/payments$/, 'Duyệt thanh toán'],
  [/^\/dashboard\/board\/deadlines$/, 'Phân xử thời hạn'],
  [/^\/dashboard\/board\/rankings$/, 'Xếp hạng và rủi ro'],
  [/^\/dashboard\/board\/reprints$/, 'Duyệt tái bản'],
  [/^\/dashboard\/board\/transfers$/, 'Duyệt chuyển nhượng'],
  [/^\/dashboard\/board\/audit$/, 'Lịch sử kiểm toán'],
  [/^\/dashboard\/board\/notifications$/, 'Thông báo Hội đồng'],
  [/^\/dashboard\/board\/profile$/, 'Hồ sơ thành viên Hội đồng'],

  [/^\/dashboard\/admin$/, 'Bảng điều khiển Super Admin'],
  [/^\/dashboard\/admin\/users\/[^/]+$/, 'Chi tiết người dùng'],
  [/^\/dashboard\/admin\/users$/, 'Quản lý người dùng'],
  [/^\/dashboard\/admin\/audit$/, 'Nhật ký hệ thống'],
  [/^\/dashboard\/admin\/board\/sessions\/[^/]+$/, 'Chi tiết phiên Hội đồng'],
  [/^\/dashboard\/admin\/board\/sessions$/, 'Giám sát phiên Hội đồng'],
  [/^\/dashboard\/admin\/board\/decisions\/[^/]+$/, 'Chi tiết quyết định Hội đồng'],
  [/^\/dashboard\/admin\/board\/decisions$/, 'Giám sát quyết định Hội đồng'],
  [/^\/dashboard\/admin\/board\/lifecycle$/, 'Giám sát vòng đời bộ truyện'],
  [/^\/dashboard\/admin\/board\/reports$/, 'Báo cáo Hội đồng'],
  [/^\/dashboard\/admin\/board\/payments$/, 'Giám sát thanh toán Hội đồng'],
  [/^\/dashboard\/admin\/board$/, 'Quản trị Hội đồng'],
  [/^\/dashboard\/admin\/operations\/monitoring$/, 'Giám sát nghiệp vụ'],
  [/^\/dashboard\/admin\/operations\/surveys$/, 'Quản trị khảo sát'],
  [/^\/dashboard\/admin\/operations\/publication-versions$/, 'Quản trị phiên bản phát hành'],
  [/^\/dashboard\/admin\/operations$/, 'Vận hành hệ thống'],
  [/^\/dashboard\/admin\/notifications$/, 'Thông báo quản trị'],
  [/^\/dashboard\/admin\/settings$/, 'Cấu hình hệ thống'],

  [/^\/publish\/[^/]+\/[^/]+\/name$/, 'Biên tập Name'],
  [/^\/publish\/[^/]+\/[^/]+\/pages$/, 'Trang bản thảo'],
  [/^\/publish\/[^/]+\/[^/]+$/, 'Không gian xuất bản']
]

export function resolveDocumentTitle(pathname: string) {
  const normalizedPath = pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname
  const pageTitle = TITLE_ROUTES.find(([pattern]) => pattern.test(normalizedPath))?.[1]
  return pageTitle && pageTitle !== 'Trang chủ' ? `${pageTitle} | ${SITE.name}` : SITE.name
}
