/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * The WDP API description
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateProposalResDtoOutput,
  SeriesResDtoOutput
} from '../../model/series';



export const getSeriesControllerCreateProposalMockHandler = (overrideResponse?: CreateProposalResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateProposalResDtoOutput> | CreateProposalResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/series/proposals', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getSeriesControllerUpdateProposalMockHandler = (overrideResponse?: SeriesResDtoOutput | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<SeriesResDtoOutput> | SeriesResDtoOutput), options?: RequestHandlerOptions) => {
  return http.put('*/series/proposals/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getSeriesControllerSubmitMockHandler = (overrideResponse?: CreateProposalResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateProposalResDtoOutput> | CreateProposalResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/series/:id/submit', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getSeriesControllerRequestProposalRevisionMockHandler = (overrideResponse?: SeriesResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SeriesResDtoOutput> | SeriesResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/series/:id/proposal/request-revision', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getSeriesControllerResubmitProposalMockHandler = (overrideResponse?: SeriesResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SeriesResDtoOutput> | SeriesResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/series/:id/proposal/resubmit', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getSeriesControllerApproveProposalMockHandler = (overrideResponse?: SeriesResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SeriesResDtoOutput> | SeriesResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/series/:id/proposal/approve', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getSeriesControllerRejectMockHandler = (overrideResponse?: SeriesResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SeriesResDtoOutput> | SeriesResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/series/:id/reject', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getSeriesControllerWithdrawMockHandler = (overrideResponse?: SeriesResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SeriesResDtoOutput> | SeriesResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/series/:id/withdraw', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getSeriesControllerPitchMockHandler = (overrideResponse?: SeriesResDtoOutput | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SeriesResDtoOutput> | SeriesResDtoOutput), options?: RequestHandlerOptions) => {
  return http.post('*/series/:id/pitch', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getSeriesMock = () => [
  getSeriesControllerCreateProposalMockHandler(),
  getSeriesControllerUpdateProposalMockHandler(),
  getSeriesControllerSubmitMockHandler(),
  getSeriesControllerRequestProposalRevisionMockHandler(),
  getSeriesControllerResubmitProposalMockHandler(),
  getSeriesControllerApproveProposalMockHandler(),
  getSeriesControllerRejectMockHandler(),
  getSeriesControllerWithdrawMockHandler(),
  getSeriesControllerPitchMockHandler()
]
