/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type { PaymentRecordResDtoOutputApprovedAt } from './paymentRecordResDtoOutputApprovedAt';
import type { PaymentRecordResDtoOutputPaymentType } from './paymentRecordResDtoOutputPaymentType';
import type { PaymentRecordResDtoOutputPaymentSource } from './paymentRecordResDtoOutputPaymentSource';
import type { PaymentRecordResDtoOutputStatus } from './paymentRecordResDtoOutputStatus';
import type { PaymentRecordResDtoOutputPaidAt } from './paymentRecordResDtoOutputPaidAt';
import type { PaymentRecordResDtoOutputCancelledAt } from './paymentRecordResDtoOutputCancelledAt';

export interface PaymentRecordResDtoOutput {
  id: string;
  contractId: string;
  /** @nullable */
  conditionId: string | null;
  receiverId: string;
  /** @nullable */
  seriesId: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  approvedBy: string | null;
  /** @nullable */
  approvedAt: PaymentRecordResDtoOutputApprovedAt;
  paymentType: PaymentRecordResDtoOutputPaymentType;
  paymentSource: PaymentRecordResDtoOutputPaymentSource;
  amount: number;
  /** @nullable */
  period: string | null;
  /** @nullable */
  paymentMethod: string | null;
  /** @nullable */
  transactionReference: string | null;
  status: PaymentRecordResDtoOutputStatus;
  /** @nullable */
  paidAt: PaymentRecordResDtoOutputPaidAt;
  /** @nullable */
  cancelledAt: PaymentRecordResDtoOutputCancelledAt;
  /** @nullable */
  cancelReason: string | null;
  /** @nullable */
  note: string | null;
  /** @nullable */
  createdBy: string | null;
  /** @nullable */
  userId: string | null;
  createdAt: unknown;
}
