/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type {
  HealthResDtoOutput
} from '../../model/health';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Process liveness probe without dependency checks
 */
export type healthControllerLiveResponse200 = {
  data: HealthResDtoOutput
  status: 200
}
    
export type healthControllerLiveResponseSuccess = (healthControllerLiveResponse200) & {
  headers: Headers;
};
;

export type healthControllerLiveResponse = (healthControllerLiveResponseSuccess)

export const getHealthControllerLiveUrl = () => {


  

  return `/health/live`
}

export const healthControllerLive = async ( options?: RequestInit): Promise<healthControllerLiveResponse> => {
  
  return customFetch<healthControllerLiveResponse>(getHealthControllerLiveUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary API readiness probe for MongoDB and Redis
 */
export type healthControllerReadyResponse200 = {
  data: HealthResDtoOutput
  status: 200
}
    
export type healthControllerReadyResponseSuccess = (healthControllerReadyResponse200) & {
  headers: Headers;
};
;

export type healthControllerReadyResponse = (healthControllerReadyResponseSuccess)

export const getHealthControllerReadyUrl = () => {


  

  return `/health/ready`
}

export const healthControllerReady = async ( options?: RequestInit): Promise<healthControllerReadyResponse> => {
  
  return customFetch<healthControllerReadyResponse>(getHealthControllerReadyUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Prometheus runtime metrics without identity or IP labels
 */
export type metricsControllerMetricsTextResponse200 = {
  data: void
  status: 200
}
    
export type metricsControllerMetricsTextResponseSuccess = (metricsControllerMetricsTextResponse200) & {
  headers: Headers;
};
;

export type metricsControllerMetricsTextResponse = (metricsControllerMetricsTextResponseSuccess)

export const getMetricsControllerMetricsTextUrl = () => {


  

  return `/metrics`
}

export const metricsControllerMetricsText = async ( options?: RequestInit): Promise<metricsControllerMetricsTextResponse> => {
  
  return customFetch<metricsControllerMetricsTextResponse>(getMetricsControllerMetricsTextUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


