/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Thành công", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "code": "Error.ProposalNotEditable",
  "message": "Không thể chỉnh sửa bản đề xuất ở trạng thái hiện tại" }             // lỗi đơn
{ "success": false, "statusCode": 422, "code": "Error.ValidationFailed",
  "message": "Địa chỉ email không hợp lệ",
  "errors": [ { "code": null, "message": "Địa chỉ email không hợp lệ", "path": "email" } ] } // lỗi field-level
```
`message` luôn là tiếng Việt để hiển thị; FE phân nhánh theo `code` ổn định. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  HealthResDtoOutput
} from '../../model/health';


export const getHealthControllerLiveResponseMock = (overrideResponse: Partial< HealthResDtoOutput > = {}): HealthResDtoOutput => ({status: faker.helpers.arrayElement(['ok'] as const), ...overrideResponse})

export const getHealthControllerReadyResponseMock = (overrideResponse: Partial< HealthResDtoOutput > = {}): HealthResDtoOutput => ({status: faker.helpers.arrayElement(['ok'] as const), ...overrideResponse})


export const getHealthControllerLiveMockHandler = (overrideResponse?: HealthResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<HealthResDtoOutput> | HealthResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/health/live', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getHealthControllerLiveResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getHealthControllerReadyMockHandler = (overrideResponse?: HealthResDtoOutput | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<HealthResDtoOutput> | HealthResDtoOutput), options?: RequestHandlerOptions) => {
  return http.get('*/health/ready', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getHealthControllerReadyResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getMetricsControllerMetricsTextMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/metrics', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getHealthMock = () => [
  getHealthControllerLiveMockHandler(),
  getHealthControllerReadyMockHandler(),
  getMetricsControllerMetricsTextMockHandler()
]
