/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WDP API
 * Mangaka Backend API.

### ⚠️ Response envelope (ĐỌC TRƯỚC)
Mọi response **thành công** đều được bọc envelope — schema/Example Value bên dưới mô tả phần **CHƯA bọc** (chính là `data`):
```jsonc
{ "success": true, "message": "Success", "data": { /* shape mô tả trong từng API *\/ } }
```
→ **FE luôn đọc `res.data`** (KHÔNG đọc thẳng field gốc). Một số API trả `message` tuỳ biến (vd xoá) → message nằm ở top-level, `data` có thể `null`.

Mọi response **lỗi** (chuẩn hoá bởi 1 filter duy nhất):
```jsonc
{ "success": false, "statusCode": 409, "message": "Error.ProposalNotEditable" }   // lỗi đơn
{ "success": false, "statusCode": 422, "message": "Invalid email",
  "errors": [ { "message": "Invalid email", "path": "email" } ] }                  // lỗi field-level
```
`message` luôn là **string**; với mã `Error.*` thì FE map sang text hiển thị. Validation fail = **422** (không phải 400).
 * OpenAPI spec version: 1.0
 */
import type {
  BoardApproveReprintBodyDto,
  CreateReprintRequestBodyDto,
  EditorApproveChapterBodyDto,
  MangakaReviewReprintBodyDto,
  ReprintChapterResDtoOutput,
  ReprintRequestControllerApproveChapterPathParameters,
  ReprintRequestControllerBoardApprovePathParameters,
  ReprintRequestControllerEditorApproveChapterPathParameters,
  ReprintRequestControllerFindAllParams,
  ReprintRequestControllerFindByIdPathParameters,
  ReprintRequestControllerGetChapterByIdPathParameters,
  ReprintRequestControllerGetChaptersPathParameters,
  ReprintRequestControllerMangakaReviewPathParameters,
  ReprintRequestControllerSubmitManuscriptPathParameters,
  ReprintRequestControllerUpdateChapterManuscriptPathParameters,
  ReprintRequestResDtoOutput,
  SubmitChapterManuscriptBodyDto
} from '../../model/reprint-requests';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Danh sách yêu cầu tái bản (filter status/seriesId)
 */
export type reprintRequestControllerFindAllResponse200 = {
  data: ReprintRequestResDtoOutput[]
  status: 200
}
    
export type reprintRequestControllerFindAllResponseSuccess = (reprintRequestControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type reprintRequestControllerFindAllResponse = (reprintRequestControllerFindAllResponseSuccess)

export const getReprintRequestControllerFindAllUrl = (params: ReprintRequestControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/reprint-requests?${stringifiedParams}` : `/reprint-requests`
}

export const reprintRequestControllerFindAll = async (params: ReprintRequestControllerFindAllParams, options?: RequestInit): Promise<reprintRequestControllerFindAllResponse> => {
  
  return customFetch<reprintRequestControllerFindAllResponse>(getReprintRequestControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Editor tạo yêu cầu tái bản (B-RPT-01)
 */
export type reprintRequestControllerCreateResponse201 = {
  data: ReprintRequestResDtoOutput
  status: 201
}
    
export type reprintRequestControllerCreateResponseSuccess = (reprintRequestControllerCreateResponse201) & {
  headers: Headers;
};
;

export type reprintRequestControllerCreateResponse = (reprintRequestControllerCreateResponseSuccess)

export const getReprintRequestControllerCreateUrl = () => {


  

  return `/reprint-requests`
}

export const reprintRequestControllerCreate = async (createReprintRequestBodyDto: CreateReprintRequestBodyDto, options?: RequestInit): Promise<reprintRequestControllerCreateResponse> => {
  
  return customFetch<reprintRequestControllerCreateResponse>(getReprintRequestControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createReprintRequestBodyDto,)
  }
);}


/**
 * @summary Chi tiết yêu cầu tái bản
 */
export type reprintRequestControllerFindByIdResponse200 = {
  data: ReprintRequestResDtoOutput
  status: 200
}
    
export type reprintRequestControllerFindByIdResponseSuccess = (reprintRequestControllerFindByIdResponse200) & {
  headers: Headers;
};
;

export type reprintRequestControllerFindByIdResponse = (reprintRequestControllerFindByIdResponseSuccess)

export const getReprintRequestControllerFindByIdUrl = ({ id }: ReprintRequestControllerFindByIdPathParameters,) => {


  

  return `/reprint-requests/${id}`
}

export const reprintRequestControllerFindById = async ({ id }: ReprintRequestControllerFindByIdPathParameters, options?: RequestInit): Promise<reprintRequestControllerFindByIdResponse> => {
  
  return customFetch<reprintRequestControllerFindByIdResponse>(getReprintRequestControllerFindByIdUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Danh sách chapter trong yêu cầu tái bản
 */
export type reprintRequestControllerGetChaptersResponse200 = {
  data: ReprintChapterResDtoOutput[]
  status: 200
}
    
export type reprintRequestControllerGetChaptersResponseSuccess = (reprintRequestControllerGetChaptersResponse200) & {
  headers: Headers;
};
;

export type reprintRequestControllerGetChaptersResponse = (reprintRequestControllerGetChaptersResponseSuccess)

export const getReprintRequestControllerGetChaptersUrl = ({ id }: ReprintRequestControllerGetChaptersPathParameters,) => {


  

  return `/reprint-requests/${id}/chapters`
}

export const reprintRequestControllerGetChapters = async ({ id }: ReprintRequestControllerGetChaptersPathParameters, options?: RequestInit): Promise<reprintRequestControllerGetChaptersResponse> => {
  
  return customFetch<reprintRequestControllerGetChaptersResponse>(getReprintRequestControllerGetChaptersUrl({ id }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Chi tiết chapter trong yêu cầu tái bản
 */
export type reprintRequestControllerGetChapterByIdResponse200 = {
  data: ReprintChapterResDtoOutput
  status: 200
}
    
export type reprintRequestControllerGetChapterByIdResponseSuccess = (reprintRequestControllerGetChapterByIdResponse200) & {
  headers: Headers;
};
;

export type reprintRequestControllerGetChapterByIdResponse = (reprintRequestControllerGetChapterByIdResponseSuccess)

export const getReprintRequestControllerGetChapterByIdUrl = ({ id, chapterId }: ReprintRequestControllerGetChapterByIdPathParameters,) => {


  

  return `/reprint-requests/${id}/chapters/${chapterId}`
}

export const reprintRequestControllerGetChapterById = async ({ id, chapterId }: ReprintRequestControllerGetChapterByIdPathParameters, options?: RequestInit): Promise<reprintRequestControllerGetChapterByIdResponse> => {
  
  return customFetch<reprintRequestControllerGetChapterByIdResponse>(getReprintRequestControllerGetChapterByIdUrl({ id, chapterId }),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Mangaka cập nhật manuscript cho chapter tái bản
 */
export type reprintRequestControllerUpdateChapterManuscriptResponse200 = {
  data: ReprintRequestResDtoOutput
  status: 200
}
    
export type reprintRequestControllerUpdateChapterManuscriptResponseSuccess = (reprintRequestControllerUpdateChapterManuscriptResponse200) & {
  headers: Headers;
};
;

export type reprintRequestControllerUpdateChapterManuscriptResponse = (reprintRequestControllerUpdateChapterManuscriptResponseSuccess)

export const getReprintRequestControllerUpdateChapterManuscriptUrl = ({ id, chapterId }: ReprintRequestControllerUpdateChapterManuscriptPathParameters,) => {


  

  return `/reprint-requests/${id}/chapters/${chapterId}/manuscript`
}

export const reprintRequestControllerUpdateChapterManuscript = async ({ id, chapterId }: ReprintRequestControllerUpdateChapterManuscriptPathParameters,
    submitChapterManuscriptBodyDto: SubmitChapterManuscriptBodyDto, options?: RequestInit): Promise<reprintRequestControllerUpdateChapterManuscriptResponse> => {
  
  return customFetch<reprintRequestControllerUpdateChapterManuscriptResponse>(getReprintRequestControllerUpdateChapterManuscriptUrl({ id, chapterId }),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      submitChapterManuscriptBodyDto,)
  }
);}


/**
 * @summary Editor duyệt chapter tái bản
 */
export type reprintRequestControllerApproveChapterResponse200 = {
  data: ReprintRequestResDtoOutput
  status: 200
}
    
export type reprintRequestControllerApproveChapterResponseSuccess = (reprintRequestControllerApproveChapterResponse200) & {
  headers: Headers;
};
;

export type reprintRequestControllerApproveChapterResponse = (reprintRequestControllerApproveChapterResponseSuccess)

export const getReprintRequestControllerApproveChapterUrl = ({ id, chapterId }: ReprintRequestControllerApproveChapterPathParameters,) => {


  

  return `/reprint-requests/${id}/chapters/${chapterId}/approve`
}

export const reprintRequestControllerApproveChapter = async ({ id, chapterId }: ReprintRequestControllerApproveChapterPathParameters,
    editorApproveChapterBodyDto: EditorApproveChapterBodyDto, options?: RequestInit): Promise<reprintRequestControllerApproveChapterResponse> => {
  
  return customFetch<reprintRequestControllerApproveChapterResponse>(getReprintRequestControllerApproveChapterUrl({ id, chapterId }),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      editorApproveChapterBodyDto,)
  }
);}


/**
 * @summary Mangaka chấp nhận/từ chối yêu cầu tái bản (B-RPT-02)
 */
export type reprintRequestControllerMangakaReviewResponse200 = {
  data: ReprintRequestResDtoOutput
  status: 200
}
    
export type reprintRequestControllerMangakaReviewResponseSuccess = (reprintRequestControllerMangakaReviewResponse200) & {
  headers: Headers;
};
;

export type reprintRequestControllerMangakaReviewResponse = (reprintRequestControllerMangakaReviewResponseSuccess)

export const getReprintRequestControllerMangakaReviewUrl = ({ id }: ReprintRequestControllerMangakaReviewPathParameters,) => {


  

  return `/reprint-requests/${id}/mangaka-review`
}

export const reprintRequestControllerMangakaReview = async ({ id }: ReprintRequestControllerMangakaReviewPathParameters,
    mangakaReviewReprintBodyDto: MangakaReviewReprintBodyDto, options?: RequestInit): Promise<reprintRequestControllerMangakaReviewResponse> => {
  
  return customFetch<reprintRequestControllerMangakaReviewResponse>(getReprintRequestControllerMangakaReviewUrl({ id }),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      mangakaReviewReprintBodyDto,)
  }
);}


/**
 * @summary Board duyệt/từ chối yêu cầu tái bản (B-RPT-02)
 */
export type reprintRequestControllerBoardApproveResponse200 = {
  data: ReprintRequestResDtoOutput
  status: 200
}
    
export type reprintRequestControllerBoardApproveResponseSuccess = (reprintRequestControllerBoardApproveResponse200) & {
  headers: Headers;
};
;

export type reprintRequestControllerBoardApproveResponse = (reprintRequestControllerBoardApproveResponseSuccess)

export const getReprintRequestControllerBoardApproveUrl = ({ id }: ReprintRequestControllerBoardApprovePathParameters,) => {


  

  return `/reprint-requests/${id}/board-approve`
}

export const reprintRequestControllerBoardApprove = async ({ id }: ReprintRequestControllerBoardApprovePathParameters,
    boardApproveReprintBodyDto: BoardApproveReprintBodyDto, options?: RequestInit): Promise<reprintRequestControllerBoardApproveResponse> => {
  
  return customFetch<reprintRequestControllerBoardApproveResponse>(getReprintRequestControllerBoardApproveUrl({ id }),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      boardApproveReprintBodyDto,)
  }
);}


/**
 * @summary Mangaka nộp manuscript sửa đổi cho chapter (B-RPT-03)
 */
export type reprintRequestControllerSubmitManuscriptResponse200 = {
  data: ReprintRequestResDtoOutput
  status: 200
}
    
export type reprintRequestControllerSubmitManuscriptResponseSuccess = (reprintRequestControllerSubmitManuscriptResponse200) & {
  headers: Headers;
};
;

export type reprintRequestControllerSubmitManuscriptResponse = (reprintRequestControllerSubmitManuscriptResponseSuccess)

export const getReprintRequestControllerSubmitManuscriptUrl = ({ id }: ReprintRequestControllerSubmitManuscriptPathParameters,) => {


  

  return `/reprint-requests/${id}/chapters/manuscript`
}

export const reprintRequestControllerSubmitManuscript = async ({ id }: ReprintRequestControllerSubmitManuscriptPathParameters,
    submitChapterManuscriptBodyDto: SubmitChapterManuscriptBodyDto, options?: RequestInit): Promise<reprintRequestControllerSubmitManuscriptResponse> => {
  
  return customFetch<reprintRequestControllerSubmitManuscriptResponse>(getReprintRequestControllerSubmitManuscriptUrl({ id }),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      submitChapterManuscriptBodyDto,)
  }
);}


/**
 * @summary Editor duyệt/yêu cầu sửa chapter tái bản (B-RPT-03/B-RPT-04)
 */
export type reprintRequestControllerEditorApproveChapterResponse200 = {
  data: ReprintRequestResDtoOutput
  status: 200
}
    
export type reprintRequestControllerEditorApproveChapterResponseSuccess = (reprintRequestControllerEditorApproveChapterResponse200) & {
  headers: Headers;
};
;

export type reprintRequestControllerEditorApproveChapterResponse = (reprintRequestControllerEditorApproveChapterResponseSuccess)

export const getReprintRequestControllerEditorApproveChapterUrl = ({ id }: ReprintRequestControllerEditorApproveChapterPathParameters,) => {


  

  return `/reprint-requests/${id}/chapters/approve`
}

export const reprintRequestControllerEditorApproveChapter = async ({ id }: ReprintRequestControllerEditorApproveChapterPathParameters,
    editorApproveChapterBodyDto: EditorApproveChapterBodyDto, options?: RequestInit): Promise<reprintRequestControllerEditorApproveChapterResponse> => {
  
  return customFetch<reprintRequestControllerEditorApproveChapterResponse>(getReprintRequestControllerEditorApproveChapterUrl({ id }),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      editorApproveChapterBodyDto,)
  }
);}


